// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package repository

import (
	"context"
	"database/sql"
)

const countCharactersByAccountID = `-- name: CountCharactersByAccountID :one
SELECT COUNT(*)
FROM character
WHERE account_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountCharactersByAccountID(ctx context.Context, accountID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCharactersByAccountID, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (login, password_hash)
VALUES ($1, $2)
RETURNING id, login, password_hash, status, token, last_logged_at, created_at, updated_at
`

type CreateAccountParams struct {
	Login        string `json:"login"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Login, arg.PasswordHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.Status,
		&i.Token,
		&i.LastLoggedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByLogin = `-- name: GetAccountByLogin :one
SELECT id, login, password_hash, status, token, last_logged_at, created_at, updated_at
FROM account
WHERE login = $1
`

func (q *Queries) GetAccountByLogin(ctx context.Context, login string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByLogin, login)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.Status,
		&i.Token,
		&i.LastLoggedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByToken = `-- name: GetAccountByToken :one
SELECT id, login, password_hash, status, token, last_logged_at, created_at, updated_at
FROM account
WHERE token = $1
`

func (q *Queries) GetAccountByToken(ctx context.Context, token sql.NullString) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByToken, token)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.Status,
		&i.Token,
		&i.LastLoggedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, login, password_hash, status, token, last_logged_at, created_at, updated_at
FROM account
`

func (q *Queries) GetAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.PasswordHash,
			&i.Status,
			&i.Token,
			&i.LastLoggedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountToken = `-- name: UpdateAccountToken :exec
UPDATE account
SET token = $1, last_logged_at = now(), updated_at = now()
WHERE id = $2
`

type UpdateAccountTokenParams struct {
	Token sql.NullString `json:"token"`
	ID    int64          `json:"id"`
}

func (q *Queries) UpdateAccountToken(ctx context.Context, arg UpdateAccountTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountToken, arg.Token, arg.ID)
	return err
}
