// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: character.sql

package repository

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/lib/pq"
)

const clearAuthToken = `-- name: ClearAuthToken :exec
UPDATE character
SET auth_token = NULL
WHERE id = $1
`

func (q *Queries) ClearAuthToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearAuthToken, id)
	return err
}

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO character (id, account_id, name, region, x, y, layer, heading, stamina, energy, shp, hhp, attributes, exp, skills,
                       discovery)
VALUES ($1, $2, $3, 1, $4, $5, 0, 0, $6, $7, 100, 100, $8::jsonb,
        $9::jsonb, $10::jsonb, $11::jsonb)
RETURNING id, account_id, name, region, x, y, layer, heading, stamina, energy, shp, hhp, attributes, exp, skills, discovery, online_time, auth_token, token_expires_at, is_online, disconnect_at, is_ghost, last_save_at, deleted_at, created_at, updated_at
`

type CreateCharacterParams struct {
	ID         int64           `json:"id"`
	AccountID  int64           `json:"account_id"`
	Name       string          `json:"name"`
	X          int             `json:"x"`
	Y          int             `json:"y"`
	Stamina    float64         `json:"stamina"`
	Energy     float64         `json:"energy"`
	Attributes json.RawMessage `json:"attributes"`
	Exp        json.RawMessage `json:"exp"`
	Skills     json.RawMessage `json:"skills"`
	Discovery  json.RawMessage `json:"discovery"`
}

func (q *Queries) CreateCharacter(ctx context.Context, arg CreateCharacterParams) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.X,
		arg.Y,
		arg.Stamina,
		arg.Energy,
		arg.Attributes,
		arg.Exp,
		arg.Skills,
		arg.Discovery,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Region,
		&i.X,
		&i.Y,
		&i.Layer,
		&i.Heading,
		&i.Stamina,
		&i.Energy,
		&i.Shp,
		&i.Hhp,
		&i.Attributes,
		&i.Exp,
		&i.Skills,
		&i.Discovery,
		&i.OnlineTime,
		&i.AuthToken,
		&i.TokenExpiresAt,
		&i.IsOnline,
		&i.DisconnectAt,
		&i.IsGhost,
		&i.LastSaveAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCharacter = `-- name: DeleteCharacter :exec
UPDATE character
SET deleted_at = now()
WHERE id = $1
  AND account_id = $2
  AND deleted_at IS NULL
`

type DeleteCharacterParams struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
}

func (q *Queries) DeleteCharacter(ctx context.Context, arg DeleteCharacterParams) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, arg.ID, arg.AccountID)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, account_id, name, region, x, y, layer, heading, stamina, energy, shp, hhp, attributes, exp, skills, discovery, online_time, auth_token, token_expires_at, is_online, disconnect_at, is_ghost, last_save_at, deleted_at, created_at, updated_at
FROM character
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCharacter(ctx context.Context, id int64) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Region,
		&i.X,
		&i.Y,
		&i.Layer,
		&i.Heading,
		&i.Stamina,
		&i.Energy,
		&i.Shp,
		&i.Hhp,
		&i.Attributes,
		&i.Exp,
		&i.Skills,
		&i.Discovery,
		&i.OnlineTime,
		&i.AuthToken,
		&i.TokenExpiresAt,
		&i.IsOnline,
		&i.DisconnectAt,
		&i.IsGhost,
		&i.LastSaveAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharacterByTokenForUpdate = `-- name: GetCharacterByTokenForUpdate :one
SELECT id, account_id, name, region, x, y, layer, heading, stamina, energy, shp, hhp, attributes, exp, skills, discovery, online_time, auth_token, token_expires_at, is_online, disconnect_at, is_ghost, last_save_at, deleted_at, created_at, updated_at
from character
where auth_token = $1
FOR UPDATE
`

func (q *Queries) GetCharacterByTokenForUpdate(ctx context.Context, authToken sql.NullString) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacterByTokenForUpdate, authToken)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Region,
		&i.X,
		&i.Y,
		&i.Layer,
		&i.Heading,
		&i.Stamina,
		&i.Energy,
		&i.Shp,
		&i.Hhp,
		&i.Attributes,
		&i.Exp,
		&i.Skills,
		&i.Discovery,
		&i.OnlineTime,
		&i.AuthToken,
		&i.TokenExpiresAt,
		&i.IsOnline,
		&i.DisconnectAt,
		&i.IsGhost,
		&i.LastSaveAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharactersByAccountID = `-- name: GetCharactersByAccountID :many
SELECT id, account_id, name, region, x, y, layer, heading, stamina, energy, shp, hhp, attributes, exp, skills, discovery, online_time, auth_token, token_expires_at, is_online, disconnect_at, is_ghost, last_save_at, deleted_at, created_at, updated_at
FROM character
WHERE account_id = $1
  AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) GetCharactersByAccountID(ctx context.Context, accountID int64) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, getCharactersByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Region,
			&i.X,
			&i.Y,
			&i.Layer,
			&i.Heading,
			&i.Stamina,
			&i.Energy,
			&i.Shp,
			&i.Hhp,
			&i.Attributes,
			&i.Exp,
			&i.Skills,
			&i.Discovery,
			&i.OnlineTime,
			&i.AuthToken,
			&i.TokenExpiresAt,
			&i.IsOnline,
			&i.DisconnectAt,
			&i.IsGhost,
			&i.LastSaveAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetOnlinePlayers = `-- name: ResetOnlinePlayers :exec
UPDATE character
SET is_online = false
WHERE region = $1
  AND is_online = true
  AND deleted_at IS NULL
`

func (q *Queries) ResetOnlinePlayers(ctx context.Context, region int) error {
	_, err := q.db.ExecContext(ctx, resetOnlinePlayers, region)
	return err
}

const setCharacterAuthToken = `-- name: SetCharacterAuthToken :exec
UPDATE character
SET auth_token = $2, token_expires_at = $3
WHERE id = $1
  AND account_id = $4
  AND deleted_at IS NULL
`

type SetCharacterAuthTokenParams struct {
	ID             int64          `json:"id"`
	AuthToken      sql.NullString `json:"auth_token"`
	TokenExpiresAt sql.NullTime   `json:"token_expires_at"`
	AccountID      int64          `json:"account_id"`
}

func (q *Queries) SetCharacterAuthToken(ctx context.Context, arg SetCharacterAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, setCharacterAuthToken,
		arg.ID,
		arg.AuthToken,
		arg.TokenExpiresAt,
		arg.AccountID,
	)
	return err
}

const setCharacterOffline = `-- name: SetCharacterOffline :exec
UPDATE character
SET is_online = false
WHERE id = $1
  AND is_online = true
  AND deleted_at IS NULL
`

func (q *Queries) SetCharacterOffline(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setCharacterOffline, id)
	return err
}

const setCharacterOnline = `-- name: SetCharacterOnline :exec
UPDATE character
SET is_online = true
WHERE id = $1
  AND is_online = false
  AND deleted_at IS NULL
`

func (q *Queries) SetCharacterOnline(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setCharacterOnline, id)
	return err
}

const updateCharacterAttributes = `-- name: UpdateCharacterAttributes :exec
UPDATE character
SET attributes = $1::jsonb,
    updated_at = now()
WHERE id = $2
  AND deleted_at IS NULL
`

type UpdateCharacterAttributesParams struct {
	Attributes json.RawMessage `json:"attributes"`
	ID         int64           `json:"id"`
}

func (q *Queries) UpdateCharacterAttributes(ctx context.Context, arg UpdateCharacterAttributesParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterAttributes, arg.Attributes, arg.ID)
	return err
}

const updateCharacterPosition = `-- name: UpdateCharacterPosition :exec
UPDATE character
SET x = $2, y = $3
WHERE id = $1
`

type UpdateCharacterPositionParams struct {
	ID int64 `json:"id"`
	X  int   `json:"x"`
	Y  int   `json:"y"`
}

func (q *Queries) UpdateCharacterPosition(ctx context.Context, arg UpdateCharacterPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterPosition, arg.ID, arg.X, arg.Y)
	return err
}

const updateCharacterPositionAndLayer = `-- name: UpdateCharacterPositionAndLayer :exec
UPDATE character
SET x = $2,
    y = $3,
    layer = $4
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateCharacterPositionAndLayerParams struct {
	ID    int64 `json:"id"`
	X     int   `json:"x"`
	Y     int   `json:"y"`
	Layer int   `json:"layer"`
}

func (q *Queries) UpdateCharacterPositionAndLayer(ctx context.Context, arg UpdateCharacterPositionAndLayerParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacterPositionAndLayer,
		arg.ID,
		arg.X,
		arg.Y,
		arg.Layer,
	)
	return err
}

const updateCharacters = `-- name: UpdateCharacters :exec
UPDATE character
SET
    x = v.x,
    y = v.y,
    heading = v.heading,
    stamina = v.stamina,
    energy = v.energy,
    shp = v.shp,
    hhp = v.hhp,
    attributes = v.attributes,
    exp = v.exp,
    skills = v.skills,
    discovery = v.discovery,
    last_save_at = now(),
    updated_at = now()
FROM (
         SELECT
             unnest($1::int[]) as id,
             unnest($2::float8[]) as x,
             unnest($3::float8[]) as y,
             unnest($4::float8[]) as heading,
             unnest($5::float8[]) as stamina,
             unnest($6::float8[]) as energy,
             unnest($7::int[]) as shp,
             unnest($8::int[]) as hhp,
             unnest($9::text[])::jsonb as attributes,
             unnest($10::text[])::jsonb as exp,
             unnest($11::text[])::jsonb as skills,
             unnest($12::text[])::jsonb as discovery
     ) AS v
WHERE character.id = v.id
`

type UpdateCharactersParams struct {
	Ids        []int     `json:"ids"`
	Xs         []float64 `json:"xs"`
	Ys         []float64 `json:"ys"`
	Headings   []float64 `json:"headings"`
	Staminas   []float64 `json:"staminas"`
	Energies   []float64 `json:"energies"`
	Shps       []int     `json:"shps"`
	Hhps       []int     `json:"hhps"`
	Attributes []string  `json:"attributes"`
	Exps       []string  `json:"exps"`
	Skills     []string  `json:"skills"`
	Discovery  []string  `json:"discovery"`
}

func (q *Queries) UpdateCharacters(ctx context.Context, arg UpdateCharactersParams) error {
	_, err := q.db.ExecContext(ctx, updateCharacters,
		pq.Array(arg.Ids),
		pq.Array(arg.Xs),
		pq.Array(arg.Ys),
		pq.Array(arg.Headings),
		pq.Array(arg.Staminas),
		pq.Array(arg.Energies),
		pq.Array(arg.Shps),
		pq.Array(arg.Hhps),
		pq.Array(arg.Attributes),
		pq.Array(arg.Exps),
		pq.Array(arg.Skills),
		pq.Array(arg.Discovery),
	)
	return err
}
