// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Account struct {
	ID           int64          `json:"id"`
	Login        string         `json:"login"`
	PasswordHash string         `json:"password_hash"`
	Status       sql.NullInt16  `json:"status"`
	Token        sql.NullString `json:"token"`
	LastLoggedAt sql.NullTime   `json:"last_logged_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type BuildSite struct {
	ID                  int64           `json:"id"`
	ObjectID            int64           `json:"object_id"`
	RecipeID            int32           `json:"recipe_id"`
	BuilderID           sql.NullInt64   `json:"builder_id"`
	BuildPointsTotal    int32           `json:"build_points_total"`
	BuildPointsProvided sql.NullInt32   `json:"build_points_provided"`
	BuildPointsCurrent  sql.NullInt32   `json:"build_points_current"`
	Status              sql.NullInt16   `json:"status"`
	RequiredItems       json.RawMessage `json:"required_items"`
	StartedAt           sql.NullTime    `json:"started_at"`
	CompletedAt         sql.NullTime    `json:"completed_at"`
}

type Character struct {
	ID             int64                 `json:"id"`
	AccountID      int64                 `json:"account_id"`
	Name           string                `json:"name"`
	Region         int32                 `json:"region"`
	X              int32                 `json:"x"`
	Y              int32                 `json:"y"`
	Layer          int32                 `json:"layer"`
	Heading        int16                 `json:"heading"`
	Stamina        int32                 `json:"stamina"`
	Shp            int32                 `json:"shp"`
	Hhp            int32                 `json:"hhp"`
	Paperdoll      pqtype.NullRawMessage `json:"paperdoll"`
	Inventory      pqtype.NullRawMessage `json:"inventory"`
	ExpNature      sql.NullInt64         `json:"exp_nature"`
	ExpIndustry    sql.NullInt64         `json:"exp_industry"`
	ExpCombat      sql.NullInt64         `json:"exp_combat"`
	OnlineTime     int64                 `json:"online_time"`
	AuthToken      sql.NullString        `json:"auth_token"`
	TokenExpiresAt sql.NullTime          `json:"token_expires_at"`
	IsOnline       sql.NullBool          `json:"is_online"`
	DisconnectAt   sql.NullTime          `json:"disconnect_at"`
	IsGhost        sql.NullBool          `json:"is_ghost"`
	LastSaveAt     sql.NullTime          `json:"last_save_at"`
	DeletedAt      sql.NullTime          `json:"deleted_at"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      sql.NullTime          `json:"updated_at"`
}

type Chat struct {
	ID         int64         `json:"id"`
	Channel    int16         `json:"channel"`
	SenderID   int64         `json:"sender_id"`
	ReceiverID sql.NullInt64 `json:"receiver_id"`
	Region     int32         `json:"region"`
	X          int32         `json:"x"`
	Y          int32         `json:"y"`
	Layer      int16         `json:"layer"`
	Message    string        `json:"message"`
	CreatedAt  time.Time     `json:"created_at"`
}

type ChatDefault struct {
	ID         int64         `json:"id"`
	Channel    int16         `json:"channel"`
	SenderID   int64         `json:"sender_id"`
	ReceiverID sql.NullInt64 `json:"receiver_id"`
	Region     int32         `json:"region"`
	X          int32         `json:"x"`
	Y          int32         `json:"y"`
	Layer      int16         `json:"layer"`
	Message    string        `json:"message"`
	CreatedAt  time.Time     `json:"created_at"`
}

type Chunk struct {
	Region      int32         `json:"region"`
	X           int32         `json:"x"`
	Y           int32         `json:"y"`
	Layer       int32         `json:"layer"`
	Version     sql.NullInt32 `json:"version"`
	LastTick    int64         `json:"last_tick"`
	LastSavedAt sql.NullTime  `json:"last_saved_at"`
	TilesData   []byte        `json:"tiles_data"`
	EntityCount sql.NullInt32 `json:"entity_count"`
}

type Container struct {
	ID          int64           `json:"id"`
	OwnerID     int64           `json:"owner_id"`
	OwnerType   int16           `json:"owner_type"`
	ContainerID int64           `json:"container_id"`
	Width       int32           `json:"width"`
	Height      int32           `json:"height"`
	Data        json.RawMessage `json:"data"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
}

type GlobalVar struct {
	Name        string         `json:"name"`
	ValueLong   sql.NullInt64  `json:"value_long"`
	ValueString sql.NullString `json:"value_string"`
}

type Object struct {
	ID         int64                 `json:"id"`
	ObjectType int32                 `json:"object_type"`
	Region     int32                 `json:"region"`
	X          int32                 `json:"x"`
	Y          int32                 `json:"y"`
	Layer      int32                 `json:"layer"`
	ChunkX     int32                 `json:"chunk_x"`
	ChunkY     int32                 `json:"chunk_y"`
	Heading    sql.NullInt16         `json:"heading"`
	Quality    sql.NullInt16         `json:"quality"`
	HpCurrent  sql.NullInt32         `json:"hp_current"`
	HpMax      sql.NullInt32         `json:"hp_max"`
	IsStatic   sql.NullBool          `json:"is_static"`
	OwnerID    sql.NullInt64         `json:"owner_id"`
	DataJsonb  pqtype.NullRawMessage `json:"data_jsonb"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	CreateTick int64                 `json:"create_tick"`
	LastTick   int64                 `json:"last_tick"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
	DeletedAt  sql.NullTime          `json:"deleted_at"`
}

type ObjectRegion1 struct {
	ID         int64                 `json:"id"`
	ObjectType int32                 `json:"object_type"`
	Region     int32                 `json:"region"`
	X          int32                 `json:"x"`
	Y          int32                 `json:"y"`
	Layer      int32                 `json:"layer"`
	ChunkX     int32                 `json:"chunk_x"`
	ChunkY     int32                 `json:"chunk_y"`
	Heading    sql.NullInt16         `json:"heading"`
	Quality    sql.NullInt16         `json:"quality"`
	HpCurrent  sql.NullInt32         `json:"hp_current"`
	HpMax      sql.NullInt32         `json:"hp_max"`
	IsStatic   sql.NullBool          `json:"is_static"`
	OwnerID    sql.NullInt64         `json:"owner_id"`
	DataJsonb  pqtype.NullRawMessage `json:"data_jsonb"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	CreateTick int64                 `json:"create_tick"`
	LastTick   int64                 `json:"last_tick"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
	DeletedAt  sql.NullTime          `json:"deleted_at"`
}

type ObjectRegion2 struct {
	ID         int64                 `json:"id"`
	ObjectType int32                 `json:"object_type"`
	Region     int32                 `json:"region"`
	X          int32                 `json:"x"`
	Y          int32                 `json:"y"`
	Layer      int32                 `json:"layer"`
	ChunkX     int32                 `json:"chunk_x"`
	ChunkY     int32                 `json:"chunk_y"`
	Heading    sql.NullInt16         `json:"heading"`
	Quality    sql.NullInt16         `json:"quality"`
	HpCurrent  sql.NullInt32         `json:"hp_current"`
	HpMax      sql.NullInt32         `json:"hp_max"`
	IsStatic   sql.NullBool          `json:"is_static"`
	OwnerID    sql.NullInt64         `json:"owner_id"`
	DataJsonb  pqtype.NullRawMessage `json:"data_jsonb"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	CreateTick int64                 `json:"create_tick"`
	LastTick   int64                 `json:"last_tick"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
	DeletedAt  sql.NullTime          `json:"deleted_at"`
}

type Skill struct {
	CharacterID int64         `json:"character_id"`
	SkillID     int32         `json:"skill_id"`
	Experience  sql.NullInt64 `json:"experience"`
	Level       int32         `json:"level"`
	LastGainAt  sql.NullTime  `json:"last_gain_at"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}
