// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: object.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const deleteObject = `-- name: DeleteObject :exec
DELETE
FROM object
WHERE id = $1
`

func (q *Queries) DeleteObject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteObject, id)
	return err
}

const deleteObjectsByChunk = `-- name: DeleteObjectsByChunk :exec
UPDATE object
SET deleted_at = NOW()
WHERE region = $1
  AND chunk_x = $2
  AND chunk_y = $3
  AND layer = $4
  AND deleted_at IS NULL
`

type DeleteObjectsByChunkParams struct {
	Region int `json:"region"`
	ChunkX int `json:"chunk_x"`
	ChunkY int `json:"chunk_y"`
	Layer  int `json:"layer"`
}

func (q *Queries) DeleteObjectsByChunk(ctx context.Context, arg DeleteObjectsByChunkParams) error {
	_, err := q.db.ExecContext(ctx, deleteObjectsByChunk,
		arg.Region,
		arg.ChunkX,
		arg.ChunkY,
		arg.Layer,
	)
	return err
}

const getObjectByID = `-- name: GetObjectByID :one
SELECT id, object_type, region, x, y, layer, chunk_x, chunk_y, heading, quality, hp_current, hp_max, is_static, owner_id, data_jsonb, created_at, create_tick, last_tick, updated_at, deleted_at
FROM object
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetObjectByID(ctx context.Context, id int64) (Object, error) {
	row := q.db.QueryRowContext(ctx, getObjectByID, id)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.ObjectType,
		&i.Region,
		&i.X,
		&i.Y,
		&i.Layer,
		&i.ChunkX,
		&i.ChunkY,
		&i.Heading,
		&i.Quality,
		&i.HpCurrent,
		&i.HpMax,
		&i.IsStatic,
		&i.OwnerID,
		&i.DataJsonb,
		&i.CreatedAt,
		&i.CreateTick,
		&i.LastTick,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getObjectsByChunk = `-- name: GetObjectsByChunk :many
SELECT id, object_type, region, x, y, layer, chunk_x, chunk_y, heading, quality, hp_current, hp_max, is_static, owner_id, data_jsonb, created_at, create_tick, last_tick, updated_at, deleted_at
FROM object
WHERE region = $1
  AND chunk_x = $2
  AND chunk_y = $3
  AND layer = $4
  AND deleted_at IS NULL
`

type GetObjectsByChunkParams struct {
	Region int `json:"region"`
	ChunkX int `json:"chunk_x"`
	ChunkY int `json:"chunk_y"`
	Layer  int `json:"layer"`
}

func (q *Queries) GetObjectsByChunk(ctx context.Context, arg GetObjectsByChunkParams) ([]Object, error) {
	rows, err := q.db.QueryContext(ctx, getObjectsByChunk,
		arg.Region,
		arg.ChunkX,
		arg.ChunkY,
		arg.Layer,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Object
	for rows.Next() {
		var i Object
		if err := rows.Scan(
			&i.ID,
			&i.ObjectType,
			&i.Region,
			&i.X,
			&i.Y,
			&i.Layer,
			&i.ChunkX,
			&i.ChunkY,
			&i.Heading,
			&i.Quality,
			&i.HpCurrent,
			&i.HpMax,
			&i.IsStatic,
			&i.OwnerID,
			&i.DataJsonb,
			&i.CreatedAt,
			&i.CreateTick,
			&i.LastTick,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteObjectsByRegion = `-- name: HardDeleteObjectsByRegion :exec
DELETE FROM object WHERE region = $1
`

func (q *Queries) HardDeleteObjectsByRegion(ctx context.Context, region int) error {
	_, err := q.db.ExecContext(ctx, hardDeleteObjectsByRegion, region)
	return err
}

const softDeleteObject = `-- name: SoftDeleteObject :exec
UPDATE object
SET deleted_at = NOW()
WHERE region = $1 AND id = $2
`

type SoftDeleteObjectParams struct {
	Region int   `json:"region"`
	ID     int64 `json:"id"`
}

func (q *Queries) SoftDeleteObject(ctx context.Context, arg SoftDeleteObjectParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteObject, arg.Region, arg.ID)
	return err
}

const truncateObjects = `-- name: TruncateObjects :exec
TRUNCATE TABLE object
`

func (q *Queries) TruncateObjects(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateObjects)
	return err
}

const upsertObject = `-- name: UpsertObject :exec
INSERT INTO object (
    id, object_type, region, x, y, layer, chunk_x, chunk_y,
    heading, quality, hp_current, hp_max, is_static, owner_id,
    data_jsonb, create_tick, last_tick, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16, $17, NOW(), NOW()
)
ON CONFLICT (region, id) DO UPDATE SET
    object_type = EXCLUDED.object_type,
    x = EXCLUDED.x,
    y = EXCLUDED.y,
    layer = EXCLUDED.layer,
    chunk_x = EXCLUDED.chunk_x,
    chunk_y = EXCLUDED.chunk_y,
    heading = EXCLUDED.heading,
    quality = EXCLUDED.quality,
    hp_current = EXCLUDED.hp_current,
    hp_max = EXCLUDED.hp_max,
    is_static = EXCLUDED.is_static,
    owner_id = EXCLUDED.owner_id,
    data_jsonb = EXCLUDED.data_jsonb,
    last_tick = EXCLUDED.last_tick,
    updated_at = NOW()
`

type UpsertObjectParams struct {
	ID         int64                 `json:"id"`
	ObjectType int                   `json:"object_type"`
	Region     int                   `json:"region"`
	X          int                   `json:"x"`
	Y          int                   `json:"y"`
	Layer      int                   `json:"layer"`
	ChunkX     int                   `json:"chunk_x"`
	ChunkY     int                   `json:"chunk_y"`
	Heading    sql.NullInt16         `json:"heading"`
	Quality    sql.NullInt16         `json:"quality"`
	HpCurrent  sql.NullInt32         `json:"hp_current"`
	HpMax      sql.NullInt32         `json:"hp_max"`
	IsStatic   sql.NullBool          `json:"is_static"`
	OwnerID    sql.NullInt64         `json:"owner_id"`
	DataJsonb  pqtype.NullRawMessage `json:"data_jsonb"`
	CreateTick int64                 `json:"create_tick"`
	LastTick   int64                 `json:"last_tick"`
}

func (q *Queries) UpsertObject(ctx context.Context, arg UpsertObjectParams) error {
	_, err := q.db.ExecContext(ctx, upsertObject,
		arg.ID,
		arg.ObjectType,
		arg.Region,
		arg.X,
		arg.Y,
		arg.Layer,
		arg.ChunkX,
		arg.ChunkY,
		arg.Heading,
		arg.Quality,
		arg.HpCurrent,
		arg.HpMax,
		arg.IsStatic,
		arg.OwnerID,
		arg.DataJsonb,
		arg.CreateTick,
		arg.LastTick,
	)
	return err
}
