// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spot.sql

package repository

import (
	"context"

	"github.com/lib/pq"
)

const deleteSpotsByRegion = `-- name: DeleteSpotsByRegion :exec
DELETE FROM spot WHERE region = $1
`

func (q *Queries) DeleteSpotsByRegion(ctx context.Context, region int) error {
	_, err := q.db.ExecContext(ctx, deleteSpotsByRegion, region)
	return err
}

const insertSpots = `-- name: InsertSpots :exec
INSERT INTO spot (
	region, layer, spot_type, district_x, district_y,
	center_x, center_y, radius, peak_quality, last_runtime_seconds
)
SELECT $1::int, $2::int,
	   unnest($3::text[]),
	   unnest($4::int[]), unnest($5::int[]),
	   unnest($6::int[]), unnest($7::int[]),
	   unnest($8::int[]), unnest($9::smallint[]),
	   $10::bigint
`

type InsertSpotsParams struct {
	Region             int      `json:"region"`
	Layer              int      `json:"layer"`
	SpotTypes          []string `json:"spot_types"`
	DistrictXs         []int    `json:"district_xs"`
	DistrictYs         []int    `json:"district_ys"`
	CenterXs           []int    `json:"center_xs"`
	CenterYs           []int    `json:"center_ys"`
	Radii              []int    `json:"radii"`
	PeakQualities      []int16  `json:"peak_qualities"`
	LastRuntimeSeconds int64    `json:"last_runtime_seconds"`
}

// All arrays have the same length; the caller bounds each batch to 1000 rows.
// State and revision use their initial database defaults.
func (q *Queries) InsertSpots(ctx context.Context, arg InsertSpotsParams) error {
	_, err := q.db.ExecContext(ctx, insertSpots,
		arg.Region,
		arg.Layer,
		pq.Array(arg.SpotTypes),
		pq.Array(arg.DistrictXs),
		pq.Array(arg.DistrictYs),
		pq.Array(arg.CenterXs),
		pq.Array(arg.CenterYs),
		pq.Array(arg.Radii),
		pq.Array(arg.PeakQualities),
		arg.LastRuntimeSeconds,
	)
	return err
}
