// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/packets.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type C2SChat_ChatChannel int32

const (
	C2SChat_CHAT_CHANNEL_LOCAL_AREA C2SChat_ChatChannel = 0
	C2SChat_CHAT_CHANNEL_PARTY      C2SChat_ChatChannel = 1
)

// Enum value maps for C2SChat_ChatChannel.
var (
	C2SChat_ChatChannel_name = map[int32]string{
		0: "CHAT_CHANNEL_LOCAL_AREA",
		1: "CHAT_CHANNEL_PARTY",
	}
	C2SChat_ChatChannel_value = map[string]int32{
		"CHAT_CHANNEL_LOCAL_AREA": 0,
		"CHAT_CHANNEL_PARTY":      1,
	}
)

func (x C2SChat_ChatChannel) Enum() *C2SChat_ChatChannel {
	p := new(C2SChat_ChatChannel)
	*p = x
	return p
}

func (x C2SChat_ChatChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (C2SChat_ChatChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_packets_proto_enumTypes[0].Descriptor()
}

func (C2SChat_ChatChannel) Type() protoreflect.EnumType {
	return &file_proto_packets_proto_enumTypes[0]
}

func (x C2SChat_ChatChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use C2SChat_ChatChannel.Descriptor instead.
func (C2SChat_ChatChannel) EnumDescriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{3, 0}
}

type S2CError_ErrorCode int32

const (
	S2CError_ERROR_CODE_UNSPECIFIED            S2CError_ErrorCode = 0
	S2CError_ERROR_CODE_INVALID_PACKET         S2CError_ErrorCode = 1
	S2CError_ERROR_CODE_NOT_AUTHENTICATED      S2CError_ErrorCode = 2
	S2CError_ERROR_CODE_INVALID_ACTION         S2CError_ErrorCode = 3
	S2CError_ERROR_CODE_TARGET_NOT_FOUND       S2CError_ErrorCode = 4
	S2CError_ERROR_CODE_INSUFFICIENT_RESOURCES S2CError_ErrorCode = 5
	S2CError_ERROR_CODE_RATE_LIMITED           S2CError_ErrorCode = 6
)

// Enum value maps for S2CError_ErrorCode.
var (
	S2CError_ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_PACKET",
		2: "ERROR_CODE_NOT_AUTHENTICATED",
		3: "ERROR_CODE_INVALID_ACTION",
		4: "ERROR_CODE_TARGET_NOT_FOUND",
		5: "ERROR_CODE_INSUFFICIENT_RESOURCES",
		6: "ERROR_CODE_RATE_LIMITED",
	}
	S2CError_ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":            0,
		"ERROR_CODE_INVALID_PACKET":         1,
		"ERROR_CODE_NOT_AUTHENTICATED":      2,
		"ERROR_CODE_INVALID_ACTION":         3,
		"ERROR_CODE_TARGET_NOT_FOUND":       4,
		"ERROR_CODE_INSUFFICIENT_RESOURCES": 5,
		"ERROR_CODE_RATE_LIMITED":           6,
	}
)

func (x S2CError_ErrorCode) Enum() *S2CError_ErrorCode {
	p := new(S2CError_ErrorCode)
	*p = x
	return p
}

func (x S2CError_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (S2CError_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_packets_proto_enumTypes[1].Descriptor()
}

func (S2CError_ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_packets_proto_enumTypes[1]
}

func (x S2CError_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use S2CError_ErrorCode.Descriptor instead.
func (S2CError_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{13, 0}
}

// Auth packet - sent when client connects
type C2SAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SAuth) Reset() {
	*x = C2SAuth{}
	mi := &file_proto_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SAuth) ProtoMessage() {}

func (x *C2SAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SAuth.ProtoReflect.Descriptor instead.
func (*C2SAuth) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{0}
}

func (x *C2SAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Move packet - player movement request
type C2SMapClick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Btn           int32                  `protobuf:"varint,3,opt,name=btn,proto3" json:"btn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SMapClick) Reset() {
	*x = C2SMapClick{}
	mi := &file_proto_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SMapClick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMapClick) ProtoMessage() {}

func (x *C2SMapClick) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMapClick.ProtoReflect.Descriptor instead.
func (*C2SMapClick) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{1}
}

func (x *C2SMapClick) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *C2SMapClick) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *C2SMapClick) GetBtn() int32 {
	if x != nil {
		return x.Btn
	}
	return 0
}

// Click on object
type C2CObjectClick struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X     int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y     int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	// mouse button and key modifiers
	Btn           int32 `protobuf:"varint,4,opt,name=btn,proto3" json:"btn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2CObjectClick) Reset() {
	*x = C2CObjectClick{}
	mi := &file_proto_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2CObjectClick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2CObjectClick) ProtoMessage() {}

func (x *C2CObjectClick) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2CObjectClick.ProtoReflect.Descriptor instead.
func (*C2CObjectClick) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{2}
}

func (x *C2CObjectClick) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *C2CObjectClick) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *C2CObjectClick) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *C2CObjectClick) GetBtn() int32 {
	if x != nil {
		return x.Btn
	}
	return 0
}

// Chat packet - send chat message
type C2SChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Channel       C2SChat_ChatChannel    `protobuf:"varint,2,opt,name=channel,proto3,enum=proto.C2SChat_ChatChannel" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SChat) Reset() {
	*x = C2SChat{}
	mi := &file_proto_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SChat) ProtoMessage() {}

func (x *C2SChat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SChat.ProtoReflect.Descriptor instead.
func (*C2SChat) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{3}
}

func (x *C2SChat) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *C2SChat) GetChannel() C2SChat_ChatChannel {
	if x != nil {
		return x.Channel
	}
	return C2SChat_CHAT_CHANNEL_LOCAL_AREA
}

// Auth response
type S2CAuthResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CharacterId   uint64                 `protobuf:"varint,3,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CAuthResult) Reset() {
	*x = S2CAuthResult{}
	mi := &file_proto_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CAuthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CAuthResult) ProtoMessage() {}

func (x *S2CAuthResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CAuthResult.ProtoReflect.Descriptor instead.
func (*S2CAuthResult) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{4}
}

func (x *S2CAuthResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *S2CAuthResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *S2CAuthResult) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

// First init world packet
type S2CWorldBootstrap struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Region         int32                  `protobuf:"varint,1,opt,name=region,proto3" json:"region,omitempty"`
	Layer          int32                  `protobuf:"varint,2,opt,name=layer,proto3" json:"layer,omitempty"` // 0, -1, -2
	PlayerEntityId int32                  `protobuf:"varint,3,opt,name=player_entity_id,json=playerEntityId,proto3" json:"player_entity_id,omitempty"`
	WorldTick      uint64                 `protobuf:"varint,4,opt,name=world_tick,json=worldTick,proto3" json:"world_tick,omitempty"`
	ChunkTileSize  int32                  `protobuf:"varint,5,opt,name=chunk_tile_size,json=chunkTileSize,proto3" json:"chunk_tile_size,omitempty"` // const -> CHUNK_SIZE
	CoordPerTile   int32                  `protobuf:"varint,6,opt,name=coord_per_tile,json=coordPerTile,proto3" json:"coord_per_tile,omitempty"`    // const -> COORD_PER_TILE
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2CWorldBootstrap) Reset() {
	*x = S2CWorldBootstrap{}
	mi := &file_proto_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CWorldBootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CWorldBootstrap) ProtoMessage() {}

func (x *S2CWorldBootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CWorldBootstrap.ProtoReflect.Descriptor instead.
func (*S2CWorldBootstrap) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{5}
}

func (x *S2CWorldBootstrap) GetRegion() int32 {
	if x != nil {
		return x.Region
	}
	return 0
}

func (x *S2CWorldBootstrap) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *S2CWorldBootstrap) GetPlayerEntityId() int32 {
	if x != nil {
		return x.PlayerEntityId
	}
	return 0
}

func (x *S2CWorldBootstrap) GetWorldTick() uint64 {
	if x != nil {
		return x.WorldTick
	}
	return 0
}

func (x *S2CWorldBootstrap) GetChunkTileSize() int32 {
	if x != nil {
		return x.ChunkTileSize
	}
	return 0
}

func (x *S2CWorldBootstrap) GetCoordPerTile() int32 {
	if x != nil {
		return x.CoordPerTile
	}
	return 0
}

// When all init data sent and can begin render
type S2CInitialDataComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CInitialDataComplete) Reset() {
	*x = S2CInitialDataComplete{}
	mi := &file_proto_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CInitialDataComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CInitialDataComplete) ProtoMessage() {}

func (x *S2CInitialDataComplete) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CInitialDataComplete.ProtoReflect.Descriptor instead.
func (*S2CInitialDataComplete) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{6}
}

// Entity spawn
type S2CObjectAdd struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	EntityId uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	TypeId   int32                  `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	X        int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y        int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	// which way the object is turned
	Heading int32 `protobuf:"varint,5,opt,name=heading,proto3" json:"heading,omitempty"`
	// resource path for render
	Resource      string `protobuf:"bytes,6,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CObjectAdd) Reset() {
	*x = S2CObjectAdd{}
	mi := &file_proto_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CObjectAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CObjectAdd) ProtoMessage() {}

func (x *S2CObjectAdd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CObjectAdd.ProtoReflect.Descriptor instead.
func (*S2CObjectAdd) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{7}
}

func (x *S2CObjectAdd) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *S2CObjectAdd) GetTypeId() int32 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *S2CObjectAdd) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *S2CObjectAdd) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *S2CObjectAdd) GetHeading() int32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *S2CObjectAdd) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

// Entity despawn
type S2CObjectDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CObjectDelete) Reset() {
	*x = S2CObjectDelete{}
	mi := &file_proto_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CObjectDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CObjectDelete) ProtoMessage() {}

func (x *S2CObjectDelete) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CObjectDelete.ProtoReflect.Descriptor instead.
func (*S2CObjectDelete) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{8}
}

func (x *S2CObjectDelete) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

// Entity position update
type S2CObjectMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CObjectMove) Reset() {
	*x = S2CObjectMove{}
	mi := &file_proto_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CObjectMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CObjectMove) ProtoMessage() {}

func (x *S2CObjectMove) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CObjectMove.ProtoReflect.Descriptor instead.
func (*S2CObjectMove) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{9}
}

func (x *S2CObjectMove) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *S2CObjectMove) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *S2CObjectMove) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Inventory update (open inventory window if not exists on the screen, update content if opened)
type S2CInventory struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Id            uint64                        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                        `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Width         int32                         `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                         `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Slots         []*S2CInventory_InventorySlot `protobuf:"bytes,5,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CInventory) Reset() {
	*x = S2CInventory{}
	mi := &file_proto_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CInventory) ProtoMessage() {}

func (x *S2CInventory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CInventory.ProtoReflect.Descriptor instead.
func (*S2CInventory) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{10}
}

func (x *S2CInventory) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *S2CInventory) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *S2CInventory) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *S2CInventory) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *S2CInventory) GetSlots() []*S2CInventory_InventorySlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

// Chunk data
type S2CChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkX        int32                  `protobuf:"varint,1,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkY        int32                  `protobuf:"varint,2,opt,name=chunk_y,json=chunkY,proto3" json:"chunk_y,omitempty"`
	TileData      []byte                 `protobuf:"bytes,3,opt,name=tile_data,json=tileData,proto3" json:"tile_data,omitempty"` // compressed tile data
	Entities      []*S2CObjectAdd        `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CChunk) Reset() {
	*x = S2CChunk{}
	mi := &file_proto_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CChunk) ProtoMessage() {}

func (x *S2CChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CChunk.ProtoReflect.Descriptor instead.
func (*S2CChunk) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{11}
}

func (x *S2CChunk) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *S2CChunk) GetChunkY() int32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

func (x *S2CChunk) GetTileData() []byte {
	if x != nil {
		return x.TileData
	}
	return nil
}

func (x *S2CChunk) GetEntities() []*S2CObjectAdd {
	if x != nil {
		return x.Entities
	}
	return nil
}

// Chat message from server
type S2CChatMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName    string                 `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Channel       C2SChat_ChatChannel    `protobuf:"varint,4,opt,name=channel,proto3,enum=proto.C2SChat_ChatChannel" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CChatMsg) Reset() {
	*x = S2CChatMsg{}
	mi := &file_proto_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CChatMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CChatMsg) ProtoMessage() {}

func (x *S2CChatMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CChatMsg.ProtoReflect.Descriptor instead.
func (*S2CChatMsg) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{12}
}

func (x *S2CChatMsg) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *S2CChatMsg) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *S2CChatMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *S2CChatMsg) GetChannel() C2SChat_ChatChannel {
	if x != nil {
		return x.Channel
	}
	return C2SChat_CHAT_CHANNEL_LOCAL_AREA
}

// Error message
type S2CError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          S2CError_ErrorCode     `protobuf:"varint,1,opt,name=code,proto3,enum=proto.S2CError_ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CError) Reset() {
	*x = S2CError{}
	mi := &file_proto_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CError) ProtoMessage() {}

func (x *S2CError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CError.ProtoReflect.Descriptor instead.
func (*S2CError) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{13}
}

func (x *S2CError) GetCode() S2CError_ErrorCode {
	if x != nil {
		return x.Code
	}
	return S2CError_ERROR_CODE_UNSPECIFIED
}

func (x *S2CError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// World state snapshot
type S2CWorldState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint64                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	ServerTime    uint64                 `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CWorldState) Reset() {
	*x = S2CWorldState{}
	mi := &file_proto_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CWorldState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CWorldState) ProtoMessage() {}

func (x *S2CWorldState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CWorldState.ProtoReflect.Descriptor instead.
func (*S2CWorldState) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{14}
}

func (x *S2CWorldState) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *S2CWorldState) GetServerTime() uint64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type S2CInventory_InventorySlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Icon          string                 `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	Quality       uint32                 `protobuf:"varint,7,opt,name=quality,proto3" json:"quality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CInventory_InventorySlot) Reset() {
	*x = S2CInventory_InventorySlot{}
	mi := &file_proto_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CInventory_InventorySlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CInventory_InventorySlot) ProtoMessage() {}

func (x *S2CInventory_InventorySlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CInventory_InventorySlot.ProtoReflect.Descriptor instead.
func (*S2CInventory_InventorySlot) Descriptor() ([]byte, []int) {
	return file_proto_packets_proto_rawDescGZIP(), []int{10, 0}
}

func (x *S2CInventory_InventorySlot) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *S2CInventory_InventorySlot) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *S2CInventory_InventorySlot) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *S2CInventory_InventorySlot) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *S2CInventory_InventorySlot) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *S2CInventory_InventorySlot) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *S2CInventory_InventorySlot) GetQuality() uint32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

var File_proto_packets_proto protoreflect.FileDescriptor

const file_proto_packets_proto_rawDesc = "" +
	"\n" +
	"\x13proto/packets.proto\x12\x05proto\"\x1f\n" +
	"\aC2SAuth\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\";\n" +
	"\vC2SMapClick\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x10\n" +
	"\x03btn\x18\x03 \x01(\x05R\x03btn\"N\n" +
	"\x0eC2CObjectClick\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x10\n" +
	"\x03btn\x18\x04 \x01(\x05R\x03btn\"\x9d\x01\n" +
	"\aC2SChat\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x124\n" +
	"\achannel\x18\x02 \x01(\x0e2\x1a.proto.C2SChat.ChatChannelR\achannel\"B\n" +
	"\vChatChannel\x12\x1b\n" +
	"\x17CHAT_CHANNEL_LOCAL_AREA\x10\x00\x12\x16\n" +
	"\x12CHAT_CHANNEL_PARTY\x10\x01\"q\n" +
	"\rS2CAuthResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12!\n" +
	"\fcharacter_id\x18\x03 \x01(\x04R\vcharacterId\"\xd8\x01\n" +
	"\x11S2CWorldBootstrap\x12\x16\n" +
	"\x06region\x18\x01 \x01(\x05R\x06region\x12\x14\n" +
	"\x05layer\x18\x02 \x01(\x05R\x05layer\x12(\n" +
	"\x10player_entity_id\x18\x03 \x01(\x05R\x0eplayerEntityId\x12\x1d\n" +
	"\n" +
	"world_tick\x18\x04 \x01(\x04R\tworldTick\x12&\n" +
	"\x0fchunk_tile_size\x18\x05 \x01(\x05R\rchunkTileSize\x12$\n" +
	"\x0ecoord_per_tile\x18\x06 \x01(\x05R\fcoordPerTile\"\x18\n" +
	"\x16S2CInitialDataComplete\"\x96\x01\n" +
	"\fS2CObjectAdd\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x17\n" +
	"\atype_id\x18\x02 \x01(\x05R\x06typeId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x18\n" +
	"\aheading\x18\x05 \x01(\x05R\aheading\x12\x1a\n" +
	"\bresource\x18\x06 \x01(\tR\bresource\".\n" +
	"\x0fS2CObjectDelete\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\"H\n" +
	"\rS2CObjectMove\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"\xbe\x02\n" +
	"\fS2CInventory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x127\n" +
	"\x05slots\x18\x05 \x03(\v2!.proto.S2CInventory.InventorySlotR\x05slots\x1a\xa0\x01\n" +
	"\rInventorySlot\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\rR\x06itemId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\x12\x18\n" +
	"\aquality\x18\a \x01(\rR\aquality\"\x8a\x01\n" +
	"\bS2CChunk\x12\x17\n" +
	"\achunk_x\x18\x01 \x01(\x05R\x06chunkX\x12\x17\n" +
	"\achunk_y\x18\x02 \x01(\x05R\x06chunkY\x12\x1b\n" +
	"\ttile_data\x18\x03 \x01(\fR\btileData\x12/\n" +
	"\bentities\x18\x04 \x03(\v2\x13.proto.S2CObjectAddR\bentities\"\x9a\x01\n" +
	"\n" +
	"S2CChatMsg\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x02 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x124\n" +
	"\achannel\x18\x04 \x01(\x0e2\x1a.proto.C2SChat.ChatChannelR\achannel\"\xc2\x02\n" +
	"\bS2CError\x12-\n" +
	"\x04code\x18\x01 \x01(\x0e2\x19.proto.S2CError.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xec\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ERROR_CODE_INVALID_PACKET\x10\x01\x12 \n" +
	"\x1cERROR_CODE_NOT_AUTHENTICATED\x10\x02\x12\x1d\n" +
	"\x19ERROR_CODE_INVALID_ACTION\x10\x03\x12\x1f\n" +
	"\x1bERROR_CODE_TARGET_NOT_FOUND\x10\x04\x12%\n" +
	"!ERROR_CODE_INSUFFICIENT_RESOURCES\x10\x05\x12\x1b\n" +
	"\x17ERROR_CODE_RATE_LIMITED\x10\x06\"D\n" +
	"\rS2CWorldState\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x04R\x04tick\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x04R\n" +
	"serverTimeB\x17Z\x15origin/internal/protob\x06proto3"

var (
	file_proto_packets_proto_rawDescOnce sync.Once
	file_proto_packets_proto_rawDescData []byte
)

func file_proto_packets_proto_rawDescGZIP() []byte {
	file_proto_packets_proto_rawDescOnce.Do(func() {
		file_proto_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_packets_proto_rawDesc), len(file_proto_packets_proto_rawDesc)))
	})
	return file_proto_packets_proto_rawDescData
}

var file_proto_packets_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_packets_proto_goTypes = []any{
	(C2SChat_ChatChannel)(0),           // 0: proto.C2SChat.ChatChannel
	(S2CError_ErrorCode)(0),            // 1: proto.S2CError.ErrorCode
	(*C2SAuth)(nil),                    // 2: proto.C2SAuth
	(*C2SMapClick)(nil),                // 3: proto.C2SMapClick
	(*C2CObjectClick)(nil),             // 4: proto.C2CObjectClick
	(*C2SChat)(nil),                    // 5: proto.C2SChat
	(*S2CAuthResult)(nil),              // 6: proto.S2CAuthResult
	(*S2CWorldBootstrap)(nil),          // 7: proto.S2CWorldBootstrap
	(*S2CInitialDataComplete)(nil),     // 8: proto.S2CInitialDataComplete
	(*S2CObjectAdd)(nil),               // 9: proto.S2CObjectAdd
	(*S2CObjectDelete)(nil),            // 10: proto.S2CObjectDelete
	(*S2CObjectMove)(nil),              // 11: proto.S2CObjectMove
	(*S2CInventory)(nil),               // 12: proto.S2CInventory
	(*S2CChunk)(nil),                   // 13: proto.S2CChunk
	(*S2CChatMsg)(nil),                 // 14: proto.S2CChatMsg
	(*S2CError)(nil),                   // 15: proto.S2CError
	(*S2CWorldState)(nil),              // 16: proto.S2CWorldState
	(*S2CInventory_InventorySlot)(nil), // 17: proto.S2CInventory.InventorySlot
}
var file_proto_packets_proto_depIdxs = []int32{
	0,  // 0: proto.C2SChat.channel:type_name -> proto.C2SChat.ChatChannel
	17, // 1: proto.S2CInventory.slots:type_name -> proto.S2CInventory.InventorySlot
	9,  // 2: proto.S2CChunk.entities:type_name -> proto.S2CObjectAdd
	0,  // 3: proto.S2CChatMsg.channel:type_name -> proto.C2SChat.ChatChannel
	1,  // 4: proto.S2CError.code:type_name -> proto.S2CError.ErrorCode
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_packets_proto_init() }
func file_proto_packets_proto_init() {
	if File_proto_packets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_packets_proto_rawDesc), len(file_proto_packets_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_packets_proto_goTypes,
		DependencyIndexes: file_proto_packets_proto_depIdxs,
		EnumInfos:         file_proto_packets_proto_enumTypes,
		MessageInfos:      file_proto_packets_proto_msgTypes,
	}.Build()
	File_proto_packets_proto = out.File
	file_proto_packets_proto_goTypes = nil
	file_proto_packets_proto_depIdxs = nil
}
