// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/packets.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MovementMode int32

const (
	MovementMode_MOVE_MODE_WALK     MovementMode = 0
	MovementMode_MOVE_MODE_RUN      MovementMode = 1
	MovementMode_MOVE_MODE_FAST_RUN MovementMode = 2
	MovementMode_MOVE_MODE_SWIM     MovementMode = 3
)

// Enum value maps for MovementMode.
var (
	MovementMode_name = map[int32]string{
		0: "MOVE_MODE_WALK",
		1: "MOVE_MODE_RUN",
		2: "MOVE_MODE_FAST_RUN",
		3: "MOVE_MODE_SWIM",
	}
	MovementMode_value = map[string]int32{
		"MOVE_MODE_WALK":     0,
		"MOVE_MODE_RUN":      1,
		"MOVE_MODE_FAST_RUN": 2,
		"MOVE_MODE_SWIM":     3,
	}
)

func (x MovementMode) Enum() *MovementMode {
	p := new(MovementMode)
	*p = x
	return p
}

func (x MovementMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MovementMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_packets_proto_enumTypes[0].Descriptor()
}

func (MovementMode) Type() protoreflect.EnumType {
	return &file_api_proto_packets_proto_enumTypes[0]
}

func (x MovementMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MovementMode.Descriptor instead.
func (MovementMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{0}
}

type EquipSlot int32

const (
	EquipSlot_EQUIP_SLOT_NONE       EquipSlot = 0
	EquipSlot_EQUIP_SLOT_HEAD       EquipSlot = 1
	EquipSlot_EQUIP_SLOT_CHEST      EquipSlot = 2
	EquipSlot_EQUIP_SLOT_LEGS       EquipSlot = 3
	EquipSlot_EQUIP_SLOT_FEET       EquipSlot = 4
	EquipSlot_EQUIP_SLOT_HANDS      EquipSlot = 5
	EquipSlot_EQUIP_SLOT_LEFT_HAND  EquipSlot = 6
	EquipSlot_EQUIP_SLOT_RIGHT_HAND EquipSlot = 7
	EquipSlot_EQUIP_SLOT_BACK       EquipSlot = 8
	EquipSlot_EQUIP_SLOT_NECK       EquipSlot = 9
	EquipSlot_EQUIP_SLOT_RING_1     EquipSlot = 10
	EquipSlot_EQUIP_SLOT_RING_2     EquipSlot = 11
)

// Enum value maps for EquipSlot.
var (
	EquipSlot_name = map[int32]string{
		0:  "EQUIP_SLOT_NONE",
		1:  "EQUIP_SLOT_HEAD",
		2:  "EQUIP_SLOT_CHEST",
		3:  "EQUIP_SLOT_LEGS",
		4:  "EQUIP_SLOT_FEET",
		5:  "EQUIP_SLOT_HANDS",
		6:  "EQUIP_SLOT_LEFT_HAND",
		7:  "EQUIP_SLOT_RIGHT_HAND",
		8:  "EQUIP_SLOT_BACK",
		9:  "EQUIP_SLOT_NECK",
		10: "EQUIP_SLOT_RING_1",
		11: "EQUIP_SLOT_RING_2",
	}
	EquipSlot_value = map[string]int32{
		"EQUIP_SLOT_NONE":       0,
		"EQUIP_SLOT_HEAD":       1,
		"EQUIP_SLOT_CHEST":      2,
		"EQUIP_SLOT_LEGS":       3,
		"EQUIP_SLOT_FEET":       4,
		"EQUIP_SLOT_HANDS":      5,
		"EQUIP_SLOT_LEFT_HAND":  6,
		"EQUIP_SLOT_RIGHT_HAND": 7,
		"EQUIP_SLOT_BACK":       8,
		"EQUIP_SLOT_NECK":       9,
		"EQUIP_SLOT_RING_1":     10,
		"EQUIP_SLOT_RING_2":     11,
	}
)

func (x EquipSlot) Enum() *EquipSlot {
	p := new(EquipSlot)
	*p = x
	return p
}

func (x EquipSlot) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EquipSlot) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_packets_proto_enumTypes[1].Descriptor()
}

func (EquipSlot) Type() protoreflect.EnumType {
	return &file_api_proto_packets_proto_enumTypes[1]
}

func (x EquipSlot) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EquipSlot.Descriptor instead.
func (EquipSlot) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{1}
}

type ExpType int32

const (
	ExpType_EXP_TYPE_NATURE   ExpType = 0
	ExpType_EXP_TYPE_INDUSTRY ExpType = 1
	ExpType_EXP_TYPE_COMBAT   ExpType = 2
)

// Enum value maps for ExpType.
var (
	ExpType_name = map[int32]string{
		0: "EXP_TYPE_NATURE",
		1: "EXP_TYPE_INDUSTRY",
		2: "EXP_TYPE_COMBAT",
	}
	ExpType_value = map[string]int32{
		"EXP_TYPE_NATURE":   0,
		"EXP_TYPE_INDUSTRY": 1,
		"EXP_TYPE_COMBAT":   2,
	}
)

func (x ExpType) Enum() *ExpType {
	p := new(ExpType)
	*p = x
	return p
}

func (x ExpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExpType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_packets_proto_enumTypes[2].Descriptor()
}

func (ExpType) Type() protoreflect.EnumType {
	return &file_api_proto_packets_proto_enumTypes[2]
}

func (x ExpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExpType.Descriptor instead.
func (ExpType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{2}
}

type WeatherType int32

const (
	WeatherType_WEATHER_TYPE_CLEAR WeatherType = 0
	WeatherType_WEATHER_TYPE_RAIN  WeatherType = 1
	WeatherType_WEATHER_TYPE_FOG   WeatherType = 2
	WeatherType_WEATHER_TYPE_STORM WeatherType = 3
	WeatherType_WEATHER_TYPE_SNOW  WeatherType = 4
)

// Enum value maps for WeatherType.
var (
	WeatherType_name = map[int32]string{
		0: "WEATHER_TYPE_CLEAR",
		1: "WEATHER_TYPE_RAIN",
		2: "WEATHER_TYPE_FOG",
		3: "WEATHER_TYPE_STORM",
		4: "WEATHER_TYPE_SNOW",
	}
	WeatherType_value = map[string]int32{
		"WEATHER_TYPE_CLEAR": 0,
		"WEATHER_TYPE_RAIN":  1,
		"WEATHER_TYPE_FOG":   2,
		"WEATHER_TYPE_STORM": 3,
		"WEATHER_TYPE_SNOW":  4,
	}
)

func (x WeatherType) Enum() *WeatherType {
	p := new(WeatherType)
	*p = x
	return p
}

func (x WeatherType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeatherType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_packets_proto_enumTypes[3].Descriptor()
}

func (WeatherType) Type() protoreflect.EnumType {
	return &file_api_proto_packets_proto_enumTypes[3]
}

func (x WeatherType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeatherType.Descriptor instead.
func (WeatherType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{3}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_NONE                   ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_REQUEST        ErrorCode = 1
	ErrorCode_ERROR_CODE_NOT_AUTHENTICATED      ErrorCode = 2
	ErrorCode_ERROR_CODE_ENTITY_NOT_FOUND       ErrorCode = 3
	ErrorCode_ERROR_CODE_OUT_OF_RANGE           ErrorCode = 4
	ErrorCode_ERROR_CODE_INSUFFICIENT_RESOURCES ErrorCode = 5
	ErrorCode_ERROR_CODE_INVENTORY_FULL         ErrorCode = 6
	ErrorCode_ERROR_CODE_CANNOT_INTERACT        ErrorCode = 7
	ErrorCode_ERROR_CODE_COOLDOWN_ACTIVE        ErrorCode = 8
	ErrorCode_ERROR_CODE_INSUFFICIENT_STAMINA   ErrorCode = 9
	ErrorCode_ERROR_CODE_TARGET_INVALID         ErrorCode = 10
	ErrorCode_ERROR_CODE_PATH_BLOCKED           ErrorCode = 11
	ErrorCode_ERROR_CODE_ALREADY_IN_PROGRESS    ErrorCode = 12
	ErrorCode_ERROR_CODE_BUILDING_INCOMPLETE    ErrorCode = 13
	ErrorCode_ERROR_CODE_RECIPE_UNKNOWN         ErrorCode = 14
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_NONE",
		1:  "ERROR_CODE_INVALID_REQUEST",
		2:  "ERROR_CODE_NOT_AUTHENTICATED",
		3:  "ERROR_CODE_ENTITY_NOT_FOUND",
		4:  "ERROR_CODE_OUT_OF_RANGE",
		5:  "ERROR_CODE_INSUFFICIENT_RESOURCES",
		6:  "ERROR_CODE_INVENTORY_FULL",
		7:  "ERROR_CODE_CANNOT_INTERACT",
		8:  "ERROR_CODE_COOLDOWN_ACTIVE",
		9:  "ERROR_CODE_INSUFFICIENT_STAMINA",
		10: "ERROR_CODE_TARGET_INVALID",
		11: "ERROR_CODE_PATH_BLOCKED",
		12: "ERROR_CODE_ALREADY_IN_PROGRESS",
		13: "ERROR_CODE_BUILDING_INCOMPLETE",
		14: "ERROR_CODE_RECIPE_UNKNOWN",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_NONE":                   0,
		"ERROR_CODE_INVALID_REQUEST":        1,
		"ERROR_CODE_NOT_AUTHENTICATED":      2,
		"ERROR_CODE_ENTITY_NOT_FOUND":       3,
		"ERROR_CODE_OUT_OF_RANGE":           4,
		"ERROR_CODE_INSUFFICIENT_RESOURCES": 5,
		"ERROR_CODE_INVENTORY_FULL":         6,
		"ERROR_CODE_CANNOT_INTERACT":        7,
		"ERROR_CODE_COOLDOWN_ACTIVE":        8,
		"ERROR_CODE_INSUFFICIENT_STAMINA":   9,
		"ERROR_CODE_TARGET_INVALID":         10,
		"ERROR_CODE_PATH_BLOCKED":           11,
		"ERROR_CODE_ALREADY_IN_PROGRESS":    12,
		"ERROR_CODE_BUILDING_INCOMPLETE":    13,
		"ERROR_CODE_RECIPE_UNKNOWN":         14,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_packets_proto_enumTypes[4].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_proto_packets_proto_enumTypes[4]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{4}
}

type InteractionType int32

const (
	InteractionType_AUTO           InteractionType = 0 // сервер решает
	InteractionType_GATHER         InteractionType = 1
	InteractionType_OPEN_CONTAINER InteractionType = 2
	InteractionType_USE            InteractionType = 4
	InteractionType_PICKUP         InteractionType = 5
)

// Enum value maps for InteractionType.
var (
	InteractionType_name = map[int32]string{
		0: "AUTO",
		1: "GATHER",
		2: "OPEN_CONTAINER",
		4: "USE",
		5: "PICKUP",
	}
	InteractionType_value = map[string]int32{
		"AUTO":           0,
		"GATHER":         1,
		"OPEN_CONTAINER": 2,
		"USE":            4,
		"PICKUP":         5,
	}
)

func (x InteractionType) Enum() *InteractionType {
	p := new(InteractionType)
	*p = x
	return p
}

func (x InteractionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractionType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_packets_proto_enumTypes[5].Descriptor()
}

func (InteractionType) Type() protoreflect.EnumType {
	return &file_api_proto_packets_proto_enumTypes[5]
}

func (x InteractionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractionType.Descriptor instead.
func (InteractionType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{5}
}

// Позиция в мире
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Heading       uint32                 `protobuf:"varint,3,opt,name=heading,proto3" json:"heading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_proto_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetHeading() uint32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

// Вектор направления/скорости
type Vector2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	mi := &file_api_proto_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{1}
}

func (x *Vector2) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// AABB для коллизий
type AABB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinX          int32                  `protobuf:"varint,1,opt,name=min_x,json=minX,proto3" json:"min_x,omitempty"`
	MinY          int32                  `protobuf:"varint,2,opt,name=min_y,json=minY,proto3" json:"min_y,omitempty"`
	MaxX          int32                  `protobuf:"varint,3,opt,name=max_x,json=maxX,proto3" json:"max_x,omitempty"`
	MaxY          int32                  `protobuf:"varint,4,opt,name=max_y,json=maxY,proto3" json:"max_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AABB) Reset() {
	*x = AABB{}
	mi := &file_api_proto_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AABB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AABB) ProtoMessage() {}

func (x *AABB) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AABB.ProtoReflect.Descriptor instead.
func (*AABB) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{2}
}

func (x *AABB) GetMinX() int32 {
	if x != nil {
		return x.MinX
	}
	return 0
}

func (x *AABB) GetMinY() int32 {
	if x != nil {
		return x.MinY
	}
	return 0
}

func (x *AABB) GetMaxX() int32 {
	if x != nil {
		return x.MaxX
	}
	return 0
}

func (x *AABB) GetMaxY() int32 {
	if x != nil {
		return x.MaxY
	}
	return 0
}

// Timestamp в Unix milliseconds
type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Millis        int64                  `protobuf:"varint,1,opt,name=millis,proto3" json:"millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_api_proto_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{3}
}

func (x *Timestamp) GetMillis() int64 {
	if x != nil {
		return x.Millis
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // ID типа предмета
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Quality       uint32                 `protobuf:"varint,3,opt,name=quality,proto3" json:"quality,omitempty"`
	Quantity      uint32                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Durability    uint32                 `protobuf:"varint,5,opt,name=durability,proto3" json:"durability,omitempty"` // 0-100, если применимо
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_proto_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{4}
}

func (x *Item) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Item) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Item) GetQuality() uint32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *Item) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Item) GetDurability() uint32 {
	if x != nil {
		return x.Durability
	}
	return 0
}

type InventorySlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             uint32                 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Item          *Item                  `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventorySlot) Reset() {
	*x = InventorySlot{}
	mi := &file_api_proto_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventorySlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventorySlot) ProtoMessage() {}

func (x *InventorySlot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventorySlot.ProtoReflect.Descriptor instead.
func (*InventorySlot) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{5}
}

func (x *InventorySlot) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *InventorySlot) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *InventorySlot) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Slots         []*InventorySlot       `protobuf:"bytes,3,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_api_proto_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{6}
}

func (x *Inventory) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Inventory) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Inventory) GetSlots() []*InventorySlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type PaperdollSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          EquipSlot              `protobuf:"varint,1,opt,name=slot,proto3,enum=proto.EquipSlot" json:"slot,omitempty"`
	Item          *Item                  `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaperdollSlot) Reset() {
	*x = PaperdollSlot{}
	mi := &file_api_proto_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaperdollSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaperdollSlot) ProtoMessage() {}

func (x *PaperdollSlot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaperdollSlot.ProtoReflect.Descriptor instead.
func (*PaperdollSlot) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{7}
}

func (x *PaperdollSlot) GetSlot() EquipSlot {
	if x != nil {
		return x.Slot
	}
	return EquipSlot_EQUIP_SLOT_NONE
}

func (x *PaperdollSlot) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type Paperdoll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*PaperdollSlot       `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paperdoll) Reset() {
	*x = Paperdoll{}
	mi := &file_api_proto_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paperdoll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paperdoll) ProtoMessage() {}

func (x *Paperdoll) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paperdoll.ProtoReflect.Descriptor instead.
func (*Paperdoll) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{8}
}

func (x *Paperdoll) GetSlots() []*PaperdollSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type EntityMovement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Position       *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Velocity       *Vector2               `protobuf:"bytes,2,opt,name=velocity,proto3" json:"velocity,omitempty"`
	MoveMode       MovementMode           `protobuf:"varint,4,opt,name=move_mode,json=moveMode,proto3,enum=proto.MovementMode" json:"move_mode,omitempty"`
	TargetPosition *Vector2               `protobuf:"bytes,5,opt,name=target_position,json=targetPosition,proto3,oneof" json:"target_position,omitempty"` // куда движется, если есть
	IsMoving       bool                   `protobuf:"varint,6,opt,name=is_moving,json=isMoving,proto3" json:"is_moving,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EntityMovement) Reset() {
	*x = EntityMovement{}
	mi := &file_api_proto_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMovement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMovement) ProtoMessage() {}

func (x *EntityMovement) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMovement.ProtoReflect.Descriptor instead.
func (*EntityMovement) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{9}
}

func (x *EntityMovement) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityMovement) GetVelocity() *Vector2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *EntityMovement) GetMoveMode() MovementMode {
	if x != nil {
		return x.MoveMode
	}
	return MovementMode_MOVE_MODE_WALK
}

func (x *EntityMovement) GetTargetPosition() *Vector2 {
	if x != nil {
		return x.TargetPosition
	}
	return nil
}

func (x *EntityMovement) GetIsMoving() bool {
	if x != nil {
		return x.IsMoving
	}
	return false
}

type EntityPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Position              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Size          *Vector2               `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityPosition) Reset() {
	*x = EntityPosition{}
	mi := &file_api_proto_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityPosition) ProtoMessage() {}

func (x *EntityPosition) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityPosition.ProtoReflect.Descriptor instead.
func (*EntityPosition) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{10}
}

func (x *EntityPosition) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityPosition) GetSize() *Vector2 {
	if x != nil {
		return x.Size
	}
	return nil
}

type EntityAppearance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityAppearance) Reset() {
	*x = EntityAppearance{}
	mi := &file_api_proto_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityAppearance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityAppearance) ProtoMessage() {}

func (x *EntityAppearance) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityAppearance.ProtoReflect.Descriptor instead.
func (*EntityAppearance) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{11}
}

func (x *EntityAppearance) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *EntityAppearance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChunkCoord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkCoord) Reset() {
	*x = ChunkCoord{}
	mi := &file_api_proto_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkCoord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkCoord) ProtoMessage() {}

func (x *ChunkCoord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkCoord.ProtoReflect.Descriptor instead.
func (*ChunkCoord) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{12}
}

func (x *ChunkCoord) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ChunkCoord) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type ChunkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coord         *ChunkCoord            `protobuf:"bytes,1,opt,name=coord,proto3" json:"coord,omitempty"`
	Tiles         []byte                 `protobuf:"bytes,2,opt,name=tiles,proto3" json:"tiles,omitempty"`      // compressed 128x128 tiles (можно zlib)
	Version       uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"` // для инвалидации кэша
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_api_proto_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{13}
}

func (x *ChunkData) GetCoord() *ChunkCoord {
	if x != nil {
		return x.Coord
	}
	return nil
}

func (x *ChunkData) GetTiles() []byte {
	if x != nil {
		return x.Tiles
	}
	return nil
}

func (x *ChunkData) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type MoveTo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveTo) Reset() {
	*x = MoveTo{}
	mi := &file_api_proto_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveTo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveTo) ProtoMessage() {}

func (x *MoveTo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveTo.ProtoReflect.Descriptor instead.
func (*MoveTo) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{14}
}

func (x *MoveTo) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveTo) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type MoveToEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	AutoInteract  bool                   `protobuf:"varint,2,opt,name=auto_interact,json=autoInteract,proto3" json:"auto_interact,omitempty"` // автоматически взаимодействовать при достижении
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToEntity) Reset() {
	*x = MoveToEntity{}
	mi := &file_api_proto_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToEntity) ProtoMessage() {}

func (x *MoveToEntity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToEntity.ProtoReflect.Descriptor instead.
func (*MoveToEntity) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{15}
}

func (x *MoveToEntity) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *MoveToEntity) GetAutoInteract() bool {
	if x != nil {
		return x.AutoInteract
	}
	return false
}

type Interact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Type          InteractionType        `protobuf:"varint,2,opt,name=type,proto3,enum=proto.InteractionType" json:"type,omitempty"` // optional, сервер сам определит если не указан
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interact) Reset() {
	*x = Interact{}
	mi := &file_api_proto_packets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interact) ProtoMessage() {}

func (x *Interact) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interact.ProtoReflect.Descriptor instead.
func (*Interact) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{16}
}

func (x *Interact) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *Interact) GetType() InteractionType {
	if x != nil {
		return x.Type
	}
	return InteractionType_AUTO
}

type C2S_PlayerAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*C2S_PlayerAction_MoveTo
	//	*C2S_PlayerAction_MoveToEntity
	//	*C2S_PlayerAction_Interact
	Action        isC2S_PlayerAction_Action `protobuf_oneof:"action"`
	Modifiers     uint32                    `protobuf:"varint,10,opt,name=modifiers,proto3" json:"modifiers,omitempty"` // bitflags: SHIFT=1, CTRL=2, ALT=4
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_PlayerAction) Reset() {
	*x = C2S_PlayerAction{}
	mi := &file_api_proto_packets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_PlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_PlayerAction) ProtoMessage() {}

func (x *C2S_PlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_PlayerAction.ProtoReflect.Descriptor instead.
func (*C2S_PlayerAction) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{17}
}

func (x *C2S_PlayerAction) GetAction() isC2S_PlayerAction_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *C2S_PlayerAction) GetMoveTo() *MoveTo {
	if x != nil {
		if x, ok := x.Action.(*C2S_PlayerAction_MoveTo); ok {
			return x.MoveTo
		}
	}
	return nil
}

func (x *C2S_PlayerAction) GetMoveToEntity() *MoveToEntity {
	if x != nil {
		if x, ok := x.Action.(*C2S_PlayerAction_MoveToEntity); ok {
			return x.MoveToEntity
		}
	}
	return nil
}

func (x *C2S_PlayerAction) GetInteract() *Interact {
	if x != nil {
		if x, ok := x.Action.(*C2S_PlayerAction_Interact); ok {
			return x.Interact
		}
	}
	return nil
}

func (x *C2S_PlayerAction) GetModifiers() uint32 {
	if x != nil {
		return x.Modifiers
	}
	return 0
}

type isC2S_PlayerAction_Action interface {
	isC2S_PlayerAction_Action()
}

type C2S_PlayerAction_MoveTo struct {
	MoveTo *MoveTo `protobuf:"bytes,1,opt,name=move_to,json=moveTo,proto3,oneof"`
}

type C2S_PlayerAction_MoveToEntity struct {
	MoveToEntity *MoveToEntity `protobuf:"bytes,2,opt,name=move_to_entity,json=moveToEntity,proto3,oneof"`
}

type C2S_PlayerAction_Interact struct {
	Interact *Interact `protobuf:"bytes,3,opt,name=interact,proto3,oneof"`
}

func (*C2S_PlayerAction_MoveTo) isC2S_PlayerAction_Action() {}

func (*C2S_PlayerAction_MoveToEntity) isC2S_PlayerAction_Action() {}

func (*C2S_PlayerAction_Interact) isC2S_PlayerAction_Action() {}

// Движение - отдельный поток для responsive controls
type C2S_MovementMode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          MovementMode           `protobuf:"varint,1,opt,name=mode,proto3,enum=proto.MovementMode" json:"mode,omitempty"` // WALK, RUN, FAST_RUN, SWIM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_MovementMode) Reset() {
	*x = C2S_MovementMode{}
	mi := &file_api_proto_packets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_MovementMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_MovementMode) ProtoMessage() {}

func (x *C2S_MovementMode) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_MovementMode.ProtoReflect.Descriptor instead.
func (*C2S_MovementMode) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{18}
}

func (x *C2S_MovementMode) GetMode() MovementMode {
	if x != nil {
		return x.Mode
	}
	return MovementMode_MOVE_MODE_WALK
}

type C2S_Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ClientVersion string                 `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_Auth) Reset() {
	*x = C2S_Auth{}
	mi := &file_api_proto_packets_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Auth) ProtoMessage() {}

func (x *C2S_Auth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Auth.ProtoReflect.Descriptor instead.
func (*C2S_Auth) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{19}
}

func (x *C2S_Auth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *C2S_Auth) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type C2S_Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTimeMs  int64                  `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2S_Ping) Reset() {
	*x = C2S_Ping{}
	mi := &file_api_proto_packets_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2S_Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_Ping) ProtoMessage() {}

func (x *C2S_Ping) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_Ping.ProtoReflect.Descriptor instead.
func (*C2S_Ping) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{20}
}

func (x *C2S_Ping) GetClientTimeMs() int64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

// Обёртка для всех клиентских сообщений
type ClientMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sequence uint32                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"` // sequence number для ack
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Auth
	//	*ClientMessage_Ping
	//	*ClientMessage_PlayerAction
	//	*ClientMessage_MovementMode
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_api_proto_packets_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{21}
}

func (x *ClientMessage) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetAuth() *C2S_Auth {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *ClientMessage) GetPing() *C2S_Ping {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ClientMessage) GetPlayerAction() *C2S_PlayerAction {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_PlayerAction); ok {
			return x.PlayerAction
		}
	}
	return nil
}

func (x *ClientMessage) GetMovementMode() *C2S_MovementMode {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_MovementMode); ok {
			return x.MovementMode
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Auth struct {
	Auth *C2S_Auth `protobuf:"bytes,10,opt,name=auth,proto3,oneof"`
}

type ClientMessage_Ping struct {
	Ping *C2S_Ping `protobuf:"bytes,11,opt,name=ping,proto3,oneof"`
}

type ClientMessage_PlayerAction struct {
	PlayerAction *C2S_PlayerAction `protobuf:"bytes,12,opt,name=player_action,json=playerAction,proto3,oneof"`
}

type ClientMessage_MovementMode struct {
	MovementMode *C2S_MovementMode `protobuf:"bytes,13,opt,name=movement_mode,json=movementMode,proto3,oneof"`
}

func (*ClientMessage_Auth) isClientMessage_Payload() {}

func (*ClientMessage_Ping) isClientMessage_Payload() {}

func (*ClientMessage_PlayerAction) isClientMessage_Payload() {}

func (*ClientMessage_MovementMode) isClientMessage_Payload() {}

type S2C_AuthResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_AuthResult) Reset() {
	*x = S2C_AuthResult{}
	mi := &file_api_proto_packets_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_AuthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_AuthResult) ProtoMessage() {}

func (x *S2C_AuthResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_AuthResult.ProtoReflect.Descriptor instead.
func (*S2C_AuthResult) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{22}
}

func (x *S2C_AuthResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *S2C_AuthResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type S2C_Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTimeMs  int64                  `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	ServerTimeMs  int64                  `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_Pong) Reset() {
	*x = S2C_Pong{}
	mi := &file_api_proto_packets_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Pong) ProtoMessage() {}

func (x *S2C_Pong) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Pong.ProtoReflect.Descriptor instead.
func (*S2C_Pong) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{23}
}

func (x *S2C_Pong) GetClientTimeMs() int64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

func (x *S2C_Pong) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

// when all is ready to player enter, than send chunks, entities, etc
type S2C_PlayerEnterWorld struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	EntityId     uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CoordPerTile uint32                 `protobuf:"varint,3,opt,name=coord_per_tile,json=coordPerTile,proto3" json:"coord_per_tile,omitempty"`
	ChunkSize    uint32                 `protobuf:"varint,4,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	// EntityStats stats = 4;
	// EntitySkills skills = 5;
	Inventory        *Inventory `protobuf:"bytes,6,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Paperdoll        *Paperdoll `protobuf:"bytes,7,opt,name=paperdoll,proto3" json:"paperdoll,omitempty"`
	DraggingEntityId *uint64    `protobuf:"varint,8,opt,name=dragging_entity_id,json=draggingEntityId,proto3,oneof" json:"dragging_entity_id,omitempty"` // если тащим что-то
	StreamEpoch      uint32     `protobuf:"varint,9,opt,name=stream_epoch,json=streamEpoch,proto3" json:"stream_epoch,omitempty"`                        // для защиты от гонок состояний
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *S2C_PlayerEnterWorld) Reset() {
	*x = S2C_PlayerEnterWorld{}
	mi := &file_api_proto_packets_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_PlayerEnterWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_PlayerEnterWorld) ProtoMessage() {}

func (x *S2C_PlayerEnterWorld) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_PlayerEnterWorld.ProtoReflect.Descriptor instead.
func (*S2C_PlayerEnterWorld) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{24}
}

func (x *S2C_PlayerEnterWorld) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *S2C_PlayerEnterWorld) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *S2C_PlayerEnterWorld) GetCoordPerTile() uint32 {
	if x != nil {
		return x.CoordPerTile
	}
	return 0
}

func (x *S2C_PlayerEnterWorld) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *S2C_PlayerEnterWorld) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *S2C_PlayerEnterWorld) GetPaperdoll() *Paperdoll {
	if x != nil {
		return x.Paperdoll
	}
	return nil
}

func (x *S2C_PlayerEnterWorld) GetDraggingEntityId() uint64 {
	if x != nil && x.DraggingEntityId != nil {
		return *x.DraggingEntityId
	}
	return 0
}

func (x *S2C_PlayerEnterWorld) GetStreamEpoch() uint32 {
	if x != nil {
		return x.StreamEpoch
	}
	return 0
}

type S2C_ObjectSpawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	ObjectType    int32                  `protobuf:"varint,2,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	Position      *EntityPosition        `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_ObjectSpawn) Reset() {
	*x = S2C_ObjectSpawn{}
	mi := &file_api_proto_packets_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ObjectSpawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ObjectSpawn) ProtoMessage() {}

func (x *S2C_ObjectSpawn) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ObjectSpawn.ProtoReflect.Descriptor instead.
func (*S2C_ObjectSpawn) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{25}
}

func (x *S2C_ObjectSpawn) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *S2C_ObjectSpawn) GetObjectType() int32 {
	if x != nil {
		return x.ObjectType
	}
	return 0
}

func (x *S2C_ObjectSpawn) GetPosition() *EntityPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type S2C_ObjectDespawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_ObjectDespawn) Reset() {
	*x = S2C_ObjectDespawn{}
	mi := &file_api_proto_packets_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ObjectDespawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ObjectDespawn) ProtoMessage() {}

func (x *S2C_ObjectDespawn) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ObjectDespawn.ProtoReflect.Descriptor instead.
func (*S2C_ObjectDespawn) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{26}
}

func (x *S2C_ObjectDespawn) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

type S2C_ObjectMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Movement      *EntityMovement        `protobuf:"bytes,2,opt,name=movement,proto3" json:"movement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_ObjectMove) Reset() {
	*x = S2C_ObjectMove{}
	mi := &file_api_proto_packets_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ObjectMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ObjectMove) ProtoMessage() {}

func (x *S2C_ObjectMove) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ObjectMove.ProtoReflect.Descriptor instead.
func (*S2C_ObjectMove) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{27}
}

func (x *S2C_ObjectMove) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *S2C_ObjectMove) GetMovement() *EntityMovement {
	if x != nil {
		return x.Movement
	}
	return nil
}

// on teleport, layer change - show loading screen on client, remove all chunks, entities
type S2C_PlayerLeaveWorld struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      uint64                 `protobuf:"varint,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_PlayerLeaveWorld) Reset() {
	*x = S2C_PlayerLeaveWorld{}
	mi := &file_api_proto_packets_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_PlayerLeaveWorld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_PlayerLeaveWorld) ProtoMessage() {}

func (x *S2C_PlayerLeaveWorld) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_PlayerLeaveWorld.ProtoReflect.Descriptor instead.
func (*S2C_PlayerLeaveWorld) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{28}
}

func (x *S2C_PlayerLeaveWorld) GetEntityId() uint64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

type S2C_ChunkLoad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *ChunkData             `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_ChunkLoad) Reset() {
	*x = S2C_ChunkLoad{}
	mi := &file_api_proto_packets_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ChunkLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ChunkLoad) ProtoMessage() {}

func (x *S2C_ChunkLoad) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ChunkLoad.ProtoReflect.Descriptor instead.
func (*S2C_ChunkLoad) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{29}
}

func (x *S2C_ChunkLoad) GetChunk() *ChunkData {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type S2C_ChunkUnload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coord         *ChunkCoord            `protobuf:"bytes,1,opt,name=coord,proto3" json:"coord,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_ChunkUnload) Reset() {
	*x = S2C_ChunkUnload{}
	mi := &file_api_proto_packets_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_ChunkUnload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_ChunkUnload) ProtoMessage() {}

func (x *S2C_ChunkUnload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_ChunkUnload.ProtoReflect.Descriptor instead.
func (*S2C_ChunkUnload) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{30}
}

func (x *S2C_ChunkUnload) GetCoord() *ChunkCoord {
	if x != nil {
		return x.Coord
	}
	return nil
}

type S2C_Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=proto.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2C_Error) Reset() {
	*x = S2C_Error{}
	mi := &file_api_proto_packets_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2C_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_Error) ProtoMessage() {}

func (x *S2C_Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_Error.ProtoReflect.Descriptor instead.
func (*S2C_Error) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{31}
}

func (x *S2C_Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_NONE
}

func (x *S2C_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Обёртка для всех серверных сообщений
type ServerMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sequence uint32                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"` // для ack если нужно
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_AuthResult
	//	*ServerMessage_Pong
	//	*ServerMessage_ChunkLoad
	//	*ServerMessage_ChunkUnload
	//	*ServerMessage_PlayerEnterWorld
	//	*ServerMessage_PlayerLeaveWorld
	//	*ServerMessage_ObjectSpawn
	//	*ServerMessage_ObjectDespawn
	//	*ServerMessage_ObjectMove
	//	*ServerMessage_Error
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_api_proto_packets_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_packets_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_packets_proto_rawDescGZIP(), []int{32}
}

func (x *ServerMessage) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetAuthResult() *S2C_AuthResult {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_AuthResult); ok {
			return x.AuthResult
		}
	}
	return nil
}

func (x *ServerMessage) GetPong() *S2C_Pong {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerMessage) GetChunkLoad() *S2C_ChunkLoad {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ChunkLoad); ok {
			return x.ChunkLoad
		}
	}
	return nil
}

func (x *ServerMessage) GetChunkUnload() *S2C_ChunkUnload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ChunkUnload); ok {
			return x.ChunkUnload
		}
	}
	return nil
}

func (x *ServerMessage) GetPlayerEnterWorld() *S2C_PlayerEnterWorld {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PlayerEnterWorld); ok {
			return x.PlayerEnterWorld
		}
	}
	return nil
}

func (x *ServerMessage) GetPlayerLeaveWorld() *S2C_PlayerLeaveWorld {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PlayerLeaveWorld); ok {
			return x.PlayerLeaveWorld
		}
	}
	return nil
}

func (x *ServerMessage) GetObjectSpawn() *S2C_ObjectSpawn {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ObjectSpawn); ok {
			return x.ObjectSpawn
		}
	}
	return nil
}

func (x *ServerMessage) GetObjectDespawn() *S2C_ObjectDespawn {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ObjectDespawn); ok {
			return x.ObjectDespawn
		}
	}
	return nil
}

func (x *ServerMessage) GetObjectMove() *S2C_ObjectMove {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ObjectMove); ok {
			return x.ObjectMove
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *S2C_Error {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_AuthResult struct {
	AuthResult *S2C_AuthResult `protobuf:"bytes,10,opt,name=auth_result,json=authResult,proto3,oneof"`
}

type ServerMessage_Pong struct {
	Pong *S2C_Pong `protobuf:"bytes,11,opt,name=pong,proto3,oneof"`
}

type ServerMessage_ChunkLoad struct {
	ChunkLoad *S2C_ChunkLoad `protobuf:"bytes,12,opt,name=chunk_load,json=chunkLoad,proto3,oneof"`
}

type ServerMessage_ChunkUnload struct {
	ChunkUnload *S2C_ChunkUnload `protobuf:"bytes,13,opt,name=chunk_unload,json=chunkUnload,proto3,oneof"`
}

type ServerMessage_PlayerEnterWorld struct {
	PlayerEnterWorld *S2C_PlayerEnterWorld `protobuf:"bytes,14,opt,name=player_enter_world,json=playerEnterWorld,proto3,oneof"`
}

type ServerMessage_PlayerLeaveWorld struct {
	PlayerLeaveWorld *S2C_PlayerLeaveWorld `protobuf:"bytes,15,opt,name=player_leave_world,json=playerLeaveWorld,proto3,oneof"`
}

type ServerMessage_ObjectSpawn struct {
	ObjectSpawn *S2C_ObjectSpawn `protobuf:"bytes,16,opt,name=object_spawn,json=objectSpawn,proto3,oneof"`
}

type ServerMessage_ObjectDespawn struct {
	ObjectDespawn *S2C_ObjectDespawn `protobuf:"bytes,17,opt,name=object_despawn,json=objectDespawn,proto3,oneof"`
}

type ServerMessage_ObjectMove struct {
	ObjectMove *S2C_ObjectMove `protobuf:"bytes,18,opt,name=object_move,json=objectMove,proto3,oneof"`
}

type ServerMessage_Error struct {
	// S2C_SpawnEntity spawn_entity = 13;
	// S2C_DespawnEntity despawn_entity = 14;
	// S2C_EntityUpdate entity_update = 15;
	// S2C_PlayerStateUpdate player_state = 16;
	// S2C_InventoryUpdate inventory_update = 17;
	// S2C_PaperdollUpdate paperdoll_update = 18;
	// S2C_ContainerOpen container_open = 19;
	// S2C_ContainerClose container_close = 20;
	// S2C_ContainerUpdate container_update = 21;
	// S2C_ItemPickedUp item_picked = 22;
	// S2C_ItemDropped item_dropped = 23;
	// S2C_ExpGain exp_gain = 24;
	// S2C_DamageDealt damage_dealt = 25;
	// S2C_EntityDied entity_died = 26;
	// S2C_ResourceGathered resource_gathered = 27;
	// S2C_ResourceDepleted resource_depleted = 28;
	// S2C_CraftStarted craft_started = 29;
	// S2C_CraftCompleted craft_completed = 30;
	// S2C_CraftFailed craft_failed = 31;
	// S2C_BuildSiteCreated build_site_created = 32;
	// S2C_BuildSiteUpdate build_site_update = 33;
	// S2C_BuildingCompleted building_completed = 34;
	// S2C_PlantGrowthUpdate plant_growth = 35;
	// S2C_DragStarted drag_started = 36;
	// S2C_DragStopped drag_stopped = 37;
	// S2C_VisibilityChanged visibility_changed = 38;
	// S2C_WorldStateUpdate world_state = 39;
	// S2C_ChatMessage chat = 40;
	// S2C_SystemMessage system_message = 41;
	Error *S2C_Error `protobuf:"bytes,42,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_AuthResult) isServerMessage_Payload() {}

func (*ServerMessage_Pong) isServerMessage_Payload() {}

func (*ServerMessage_ChunkLoad) isServerMessage_Payload() {}

func (*ServerMessage_ChunkUnload) isServerMessage_Payload() {}

func (*ServerMessage_PlayerEnterWorld) isServerMessage_Payload() {}

func (*ServerMessage_PlayerLeaveWorld) isServerMessage_Payload() {}

func (*ServerMessage_ObjectSpawn) isServerMessage_Payload() {}

func (*ServerMessage_ObjectDespawn) isServerMessage_Payload() {}

func (*ServerMessage_ObjectMove) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

var File_api_proto_packets_proto protoreflect.FileDescriptor

const file_api_proto_packets_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/packets.proto\x12\x05proto\"@\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x18\n" +
	"\aheading\x18\x03 \x01(\rR\aheading\"%\n" +
	"\aVector2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"Z\n" +
	"\x04AABB\x12\x13\n" +
	"\x05min_x\x18\x01 \x01(\x05R\x04minX\x12\x13\n" +
	"\x05min_y\x18\x02 \x01(\x05R\x04minY\x12\x13\n" +
	"\x05max_x\x18\x03 \x01(\x05R\x04maxX\x12\x13\n" +
	"\x05max_y\x18\x04 \x01(\x05R\x04maxY\"#\n" +
	"\tTimestamp\x12\x16\n" +
	"\x06millis\x18\x01 \x01(\x03R\x06millis\"\x91\x01\n" +
	"\x04Item\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\rR\x06itemId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x18\n" +
	"\aquality\x18\x03 \x01(\rR\aquality\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\rR\bquantity\x12\x1e\n" +
	"\n" +
	"durability\x18\x05 \x01(\rR\n" +
	"durability\"L\n" +
	"\rInventorySlot\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01y\x12\x1f\n" +
	"\x04item\x18\x03 \x01(\v2\v.proto.ItemR\x04item\"e\n" +
	"\tInventory\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12*\n" +
	"\x05slots\x18\x03 \x03(\v2\x14.proto.InventorySlotR\x05slots\"V\n" +
	"\rPaperdollSlot\x12$\n" +
	"\x04slot\x18\x01 \x01(\x0e2\x10.proto.EquipSlotR\x04slot\x12\x1f\n" +
	"\x04item\x18\x02 \x01(\v2\v.proto.ItemR\x04item\"7\n" +
	"\tPaperdoll\x12*\n" +
	"\x05slots\x18\x01 \x03(\v2\x14.proto.PaperdollSlotR\x05slots\"\x8a\x02\n" +
	"\x0eEntityMovement\x12+\n" +
	"\bposition\x18\x01 \x01(\v2\x0f.proto.PositionR\bposition\x12*\n" +
	"\bvelocity\x18\x02 \x01(\v2\x0e.proto.Vector2R\bvelocity\x120\n" +
	"\tmove_mode\x18\x04 \x01(\x0e2\x13.proto.MovementModeR\bmoveMode\x12<\n" +
	"\x0ftarget_position\x18\x05 \x01(\v2\x0e.proto.Vector2H\x00R\x0etargetPosition\x88\x01\x01\x12\x1b\n" +
	"\tis_moving\x18\x06 \x01(\bR\bisMovingB\x12\n" +
	"\x10_target_position\"a\n" +
	"\x0eEntityPosition\x12+\n" +
	"\bposition\x18\x01 \x01(\v2\x0f.proto.PositionR\bposition\x12\"\n" +
	"\x04size\x18\x02 \x01(\v2\x0e.proto.Vector2R\x04size\"B\n" +
	"\x10EntityAppearance\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"(\n" +
	"\n" +
	"ChunkCoord\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"d\n" +
	"\tChunkData\x12'\n" +
	"\x05coord\x18\x01 \x01(\v2\x11.proto.ChunkCoordR\x05coord\x12\x14\n" +
	"\x05tiles\x18\x02 \x01(\fR\x05tiles\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\"$\n" +
	"\x06MoveTo\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"P\n" +
	"\fMoveToEntity\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12#\n" +
	"\rauto_interact\x18\x02 \x01(\bR\fautoInteract\"S\n" +
	"\bInteract\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.proto.InteractionTypeR\x04type\"\xd0\x01\n" +
	"\x10C2S_PlayerAction\x12(\n" +
	"\amove_to\x18\x01 \x01(\v2\r.proto.MoveToH\x00R\x06moveTo\x12;\n" +
	"\x0emove_to_entity\x18\x02 \x01(\v2\x13.proto.MoveToEntityH\x00R\fmoveToEntity\x12-\n" +
	"\binteract\x18\x03 \x01(\v2\x0f.proto.InteractH\x00R\binteract\x12\x1c\n" +
	"\tmodifiers\x18\n" +
	" \x01(\rR\tmodifiersB\b\n" +
	"\x06action\";\n" +
	"\x10C2S_MovementMode\x12'\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x13.proto.MovementModeR\x04mode\"G\n" +
	"\bC2S_Auth\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\"0\n" +
	"\bC2S_Ping\x12$\n" +
	"\x0eclient_time_ms\x18\x01 \x01(\x03R\fclientTimeMs\"\x84\x02\n" +
	"\rClientMessage\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\x12%\n" +
	"\x04auth\x18\n" +
	" \x01(\v2\x0f.proto.C2S_AuthH\x00R\x04auth\x12%\n" +
	"\x04ping\x18\v \x01(\v2\x0f.proto.C2S_PingH\x00R\x04ping\x12>\n" +
	"\rplayer_action\x18\f \x01(\v2\x17.proto.C2S_PlayerActionH\x00R\fplayerAction\x12>\n" +
	"\rmovement_mode\x18\r \x01(\v2\x17.proto.C2S_MovementModeH\x00R\fmovementModeB\t\n" +
	"\apayload\"O\n" +
	"\x0eS2C_AuthResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"V\n" +
	"\bS2C_Pong\x12$\n" +
	"\x0eclient_time_ms\x18\x01 \x01(\x03R\fclientTimeMs\x12$\n" +
	"\x0eserver_time_ms\x18\x02 \x01(\x03R\fserverTimeMs\"\xd9\x02\n" +
	"\x14S2C_PlayerEnterWorld\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x0ecoord_per_tile\x18\x03 \x01(\rR\fcoordPerTile\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x04 \x01(\rR\tchunkSize\x12.\n" +
	"\tinventory\x18\x06 \x01(\v2\x10.proto.InventoryR\tinventory\x12.\n" +
	"\tpaperdoll\x18\a \x01(\v2\x10.proto.PaperdollR\tpaperdoll\x121\n" +
	"\x12dragging_entity_id\x18\b \x01(\x04H\x00R\x10draggingEntityId\x88\x01\x01\x12!\n" +
	"\fstream_epoch\x18\t \x01(\rR\vstreamEpochB\x15\n" +
	"\x13_dragging_entity_id\"\x82\x01\n" +
	"\x0fS2C_ObjectSpawn\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x12\x1f\n" +
	"\vobject_type\x18\x02 \x01(\x05R\n" +
	"objectType\x121\n" +
	"\bposition\x18\x03 \x01(\v2\x15.proto.EntityPositionR\bposition\"0\n" +
	"\x11S2C_ObjectDespawn\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\"`\n" +
	"\x0eS2C_ObjectMove\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\x121\n" +
	"\bmovement\x18\x02 \x01(\v2\x15.proto.EntityMovementR\bmovement\"3\n" +
	"\x14S2C_PlayerLeaveWorld\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\x04R\bentityId\"7\n" +
	"\rS2C_ChunkLoad\x12&\n" +
	"\x05chunk\x18\x01 \x01(\v2\x10.proto.ChunkDataR\x05chunk\":\n" +
	"\x0fS2C_ChunkUnload\x12'\n" +
	"\x05coord\x18\x01 \x01(\v2\x11.proto.ChunkCoordR\x05coord\"K\n" +
	"\tS2C_Error\x12$\n" +
	"\x04code\x18\x01 \x01(\x0e2\x10.proto.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x89\x05\n" +
	"\rServerMessage\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\x128\n" +
	"\vauth_result\x18\n" +
	" \x01(\v2\x15.proto.S2C_AuthResultH\x00R\n" +
	"authResult\x12%\n" +
	"\x04pong\x18\v \x01(\v2\x0f.proto.S2C_PongH\x00R\x04pong\x125\n" +
	"\n" +
	"chunk_load\x18\f \x01(\v2\x14.proto.S2C_ChunkLoadH\x00R\tchunkLoad\x12;\n" +
	"\fchunk_unload\x18\r \x01(\v2\x16.proto.S2C_ChunkUnloadH\x00R\vchunkUnload\x12K\n" +
	"\x12player_enter_world\x18\x0e \x01(\v2\x1b.proto.S2C_PlayerEnterWorldH\x00R\x10playerEnterWorld\x12K\n" +
	"\x12player_leave_world\x18\x0f \x01(\v2\x1b.proto.S2C_PlayerLeaveWorldH\x00R\x10playerLeaveWorld\x12;\n" +
	"\fobject_spawn\x18\x10 \x01(\v2\x16.proto.S2C_ObjectSpawnH\x00R\vobjectSpawn\x12A\n" +
	"\x0eobject_despawn\x18\x11 \x01(\v2\x18.proto.S2C_ObjectDespawnH\x00R\robjectDespawn\x128\n" +
	"\vobject_move\x18\x12 \x01(\v2\x15.proto.S2C_ObjectMoveH\x00R\n" +
	"objectMove\x12(\n" +
	"\x05error\x18* \x01(\v2\x10.proto.S2C_ErrorH\x00R\x05errorB\t\n" +
	"\apayload*a\n" +
	"\fMovementMode\x12\x12\n" +
	"\x0eMOVE_MODE_WALK\x10\x00\x12\x11\n" +
	"\rMOVE_MODE_RUN\x10\x01\x12\x16\n" +
	"\x12MOVE_MODE_FAST_RUN\x10\x02\x12\x12\n" +
	"\x0eMOVE_MODE_SWIM\x10\x03*\x98\x02\n" +
	"\tEquipSlot\x12\x13\n" +
	"\x0fEQUIP_SLOT_NONE\x10\x00\x12\x13\n" +
	"\x0fEQUIP_SLOT_HEAD\x10\x01\x12\x14\n" +
	"\x10EQUIP_SLOT_CHEST\x10\x02\x12\x13\n" +
	"\x0fEQUIP_SLOT_LEGS\x10\x03\x12\x13\n" +
	"\x0fEQUIP_SLOT_FEET\x10\x04\x12\x14\n" +
	"\x10EQUIP_SLOT_HANDS\x10\x05\x12\x18\n" +
	"\x14EQUIP_SLOT_LEFT_HAND\x10\x06\x12\x19\n" +
	"\x15EQUIP_SLOT_RIGHT_HAND\x10\a\x12\x13\n" +
	"\x0fEQUIP_SLOT_BACK\x10\b\x12\x13\n" +
	"\x0fEQUIP_SLOT_NECK\x10\t\x12\x15\n" +
	"\x11EQUIP_SLOT_RING_1\x10\n" +
	"\x12\x15\n" +
	"\x11EQUIP_SLOT_RING_2\x10\v*J\n" +
	"\aExpType\x12\x13\n" +
	"\x0fEXP_TYPE_NATURE\x10\x00\x12\x15\n" +
	"\x11EXP_TYPE_INDUSTRY\x10\x01\x12\x13\n" +
	"\x0fEXP_TYPE_COMBAT\x10\x02*\x81\x01\n" +
	"\vWeatherType\x12\x16\n" +
	"\x12WEATHER_TYPE_CLEAR\x10\x00\x12\x15\n" +
	"\x11WEATHER_TYPE_RAIN\x10\x01\x12\x14\n" +
	"\x10WEATHER_TYPE_FOG\x10\x02\x12\x16\n" +
	"\x12WEATHER_TYPE_STORM\x10\x03\x12\x15\n" +
	"\x11WEATHER_TYPE_SNOW\x10\x04*\xee\x03\n" +
	"\tErrorCode\x12\x13\n" +
	"\x0fERROR_CODE_NONE\x10\x00\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_REQUEST\x10\x01\x12 \n" +
	"\x1cERROR_CODE_NOT_AUTHENTICATED\x10\x02\x12\x1f\n" +
	"\x1bERROR_CODE_ENTITY_NOT_FOUND\x10\x03\x12\x1b\n" +
	"\x17ERROR_CODE_OUT_OF_RANGE\x10\x04\x12%\n" +
	"!ERROR_CODE_INSUFFICIENT_RESOURCES\x10\x05\x12\x1d\n" +
	"\x19ERROR_CODE_INVENTORY_FULL\x10\x06\x12\x1e\n" +
	"\x1aERROR_CODE_CANNOT_INTERACT\x10\a\x12\x1e\n" +
	"\x1aERROR_CODE_COOLDOWN_ACTIVE\x10\b\x12#\n" +
	"\x1fERROR_CODE_INSUFFICIENT_STAMINA\x10\t\x12\x1d\n" +
	"\x19ERROR_CODE_TARGET_INVALID\x10\n" +
	"\x12\x1b\n" +
	"\x17ERROR_CODE_PATH_BLOCKED\x10\v\x12\"\n" +
	"\x1eERROR_CODE_ALREADY_IN_PROGRESS\x10\f\x12\"\n" +
	"\x1eERROR_CODE_BUILDING_INCOMPLETE\x10\r\x12\x1d\n" +
	"\x19ERROR_CODE_RECIPE_UNKNOWN\x10\x0e*P\n" +
	"\x0fInteractionType\x12\b\n" +
	"\x04AUTO\x10\x00\x12\n" +
	"\n" +
	"\x06GATHER\x10\x01\x12\x12\n" +
	"\x0eOPEN_CONTAINER\x10\x02\x12\a\n" +
	"\x03USE\x10\x04\x12\n" +
	"\n" +
	"\x06PICKUP\x10\x05B\x1fZ\x1dorigin/internal/network/protob\x06proto3"

var (
	file_api_proto_packets_proto_rawDescOnce sync.Once
	file_api_proto_packets_proto_rawDescData []byte
)

func file_api_proto_packets_proto_rawDescGZIP() []byte {
	file_api_proto_packets_proto_rawDescOnce.Do(func() {
		file_api_proto_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_packets_proto_rawDesc), len(file_api_proto_packets_proto_rawDesc)))
	})
	return file_api_proto_packets_proto_rawDescData
}

var file_api_proto_packets_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_api_proto_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_api_proto_packets_proto_goTypes = []any{
	(MovementMode)(0),            // 0: proto.MovementMode
	(EquipSlot)(0),               // 1: proto.EquipSlot
	(ExpType)(0),                 // 2: proto.ExpType
	(WeatherType)(0),             // 3: proto.WeatherType
	(ErrorCode)(0),               // 4: proto.ErrorCode
	(InteractionType)(0),         // 5: proto.InteractionType
	(*Position)(nil),             // 6: proto.Position
	(*Vector2)(nil),              // 7: proto.Vector2
	(*AABB)(nil),                 // 8: proto.AABB
	(*Timestamp)(nil),            // 9: proto.Timestamp
	(*Item)(nil),                 // 10: proto.Item
	(*InventorySlot)(nil),        // 11: proto.InventorySlot
	(*Inventory)(nil),            // 12: proto.Inventory
	(*PaperdollSlot)(nil),        // 13: proto.PaperdollSlot
	(*Paperdoll)(nil),            // 14: proto.Paperdoll
	(*EntityMovement)(nil),       // 15: proto.EntityMovement
	(*EntityPosition)(nil),       // 16: proto.EntityPosition
	(*EntityAppearance)(nil),     // 17: proto.EntityAppearance
	(*ChunkCoord)(nil),           // 18: proto.ChunkCoord
	(*ChunkData)(nil),            // 19: proto.ChunkData
	(*MoveTo)(nil),               // 20: proto.MoveTo
	(*MoveToEntity)(nil),         // 21: proto.MoveToEntity
	(*Interact)(nil),             // 22: proto.Interact
	(*C2S_PlayerAction)(nil),     // 23: proto.C2S_PlayerAction
	(*C2S_MovementMode)(nil),     // 24: proto.C2S_MovementMode
	(*C2S_Auth)(nil),             // 25: proto.C2S_Auth
	(*C2S_Ping)(nil),             // 26: proto.C2S_Ping
	(*ClientMessage)(nil),        // 27: proto.ClientMessage
	(*S2C_AuthResult)(nil),       // 28: proto.S2C_AuthResult
	(*S2C_Pong)(nil),             // 29: proto.S2C_Pong
	(*S2C_PlayerEnterWorld)(nil), // 30: proto.S2C_PlayerEnterWorld
	(*S2C_ObjectSpawn)(nil),      // 31: proto.S2C_ObjectSpawn
	(*S2C_ObjectDespawn)(nil),    // 32: proto.S2C_ObjectDespawn
	(*S2C_ObjectMove)(nil),       // 33: proto.S2C_ObjectMove
	(*S2C_PlayerLeaveWorld)(nil), // 34: proto.S2C_PlayerLeaveWorld
	(*S2C_ChunkLoad)(nil),        // 35: proto.S2C_ChunkLoad
	(*S2C_ChunkUnload)(nil),      // 36: proto.S2C_ChunkUnload
	(*S2C_Error)(nil),            // 37: proto.S2C_Error
	(*ServerMessage)(nil),        // 38: proto.ServerMessage
}
var file_api_proto_packets_proto_depIdxs = []int32{
	10, // 0: proto.InventorySlot.item:type_name -> proto.Item
	11, // 1: proto.Inventory.slots:type_name -> proto.InventorySlot
	1,  // 2: proto.PaperdollSlot.slot:type_name -> proto.EquipSlot
	10, // 3: proto.PaperdollSlot.item:type_name -> proto.Item
	13, // 4: proto.Paperdoll.slots:type_name -> proto.PaperdollSlot
	6,  // 5: proto.EntityMovement.position:type_name -> proto.Position
	7,  // 6: proto.EntityMovement.velocity:type_name -> proto.Vector2
	0,  // 7: proto.EntityMovement.move_mode:type_name -> proto.MovementMode
	7,  // 8: proto.EntityMovement.target_position:type_name -> proto.Vector2
	6,  // 9: proto.EntityPosition.position:type_name -> proto.Position
	7,  // 10: proto.EntityPosition.size:type_name -> proto.Vector2
	18, // 11: proto.ChunkData.coord:type_name -> proto.ChunkCoord
	5,  // 12: proto.Interact.type:type_name -> proto.InteractionType
	20, // 13: proto.C2S_PlayerAction.move_to:type_name -> proto.MoveTo
	21, // 14: proto.C2S_PlayerAction.move_to_entity:type_name -> proto.MoveToEntity
	22, // 15: proto.C2S_PlayerAction.interact:type_name -> proto.Interact
	0,  // 16: proto.C2S_MovementMode.mode:type_name -> proto.MovementMode
	25, // 17: proto.ClientMessage.auth:type_name -> proto.C2S_Auth
	26, // 18: proto.ClientMessage.ping:type_name -> proto.C2S_Ping
	23, // 19: proto.ClientMessage.player_action:type_name -> proto.C2S_PlayerAction
	24, // 20: proto.ClientMessage.movement_mode:type_name -> proto.C2S_MovementMode
	12, // 21: proto.S2C_PlayerEnterWorld.inventory:type_name -> proto.Inventory
	14, // 22: proto.S2C_PlayerEnterWorld.paperdoll:type_name -> proto.Paperdoll
	16, // 23: proto.S2C_ObjectSpawn.position:type_name -> proto.EntityPosition
	15, // 24: proto.S2C_ObjectMove.movement:type_name -> proto.EntityMovement
	19, // 25: proto.S2C_ChunkLoad.chunk:type_name -> proto.ChunkData
	18, // 26: proto.S2C_ChunkUnload.coord:type_name -> proto.ChunkCoord
	4,  // 27: proto.S2C_Error.code:type_name -> proto.ErrorCode
	28, // 28: proto.ServerMessage.auth_result:type_name -> proto.S2C_AuthResult
	29, // 29: proto.ServerMessage.pong:type_name -> proto.S2C_Pong
	35, // 30: proto.ServerMessage.chunk_load:type_name -> proto.S2C_ChunkLoad
	36, // 31: proto.ServerMessage.chunk_unload:type_name -> proto.S2C_ChunkUnload
	30, // 32: proto.ServerMessage.player_enter_world:type_name -> proto.S2C_PlayerEnterWorld
	34, // 33: proto.ServerMessage.player_leave_world:type_name -> proto.S2C_PlayerLeaveWorld
	31, // 34: proto.ServerMessage.object_spawn:type_name -> proto.S2C_ObjectSpawn
	32, // 35: proto.ServerMessage.object_despawn:type_name -> proto.S2C_ObjectDespawn
	33, // 36: proto.ServerMessage.object_move:type_name -> proto.S2C_ObjectMove
	37, // 37: proto.ServerMessage.error:type_name -> proto.S2C_Error
	38, // [38:38] is the sub-list for method output_type
	38, // [38:38] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_api_proto_packets_proto_init() }
func file_api_proto_packets_proto_init() {
	if File_api_proto_packets_proto != nil {
		return
	}
	file_api_proto_packets_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_proto_packets_proto_msgTypes[17].OneofWrappers = []any{
		(*C2S_PlayerAction_MoveTo)(nil),
		(*C2S_PlayerAction_MoveToEntity)(nil),
		(*C2S_PlayerAction_Interact)(nil),
	}
	file_api_proto_packets_proto_msgTypes[21].OneofWrappers = []any{
		(*ClientMessage_Auth)(nil),
		(*ClientMessage_Ping)(nil),
		(*ClientMessage_PlayerAction)(nil),
		(*ClientMessage_MovementMode)(nil),
	}
	file_api_proto_packets_proto_msgTypes[24].OneofWrappers = []any{}
	file_api_proto_packets_proto_msgTypes[32].OneofWrappers = []any{
		(*ServerMessage_AuthResult)(nil),
		(*ServerMessage_Pong)(nil),
		(*ServerMessage_ChunkLoad)(nil),
		(*ServerMessage_ChunkUnload)(nil),
		(*ServerMessage_PlayerEnterWorld)(nil),
		(*ServerMessage_PlayerLeaveWorld)(nil),
		(*ServerMessage_ObjectSpawn)(nil),
		(*ServerMessage_ObjectDespawn)(nil),
		(*ServerMessage_ObjectMove)(nil),
		(*ServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_packets_proto_rawDesc), len(file_api_proto_packets_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_packets_proto_goTypes,
		DependencyIndexes: file_api_proto_packets_proto_depIdxs,
		EnumInfos:         file_api_proto_packets_proto_enumTypes,
		MessageInfos:      file_api_proto_packets_proto_msgTypes,
	}.Build()
	File_api_proto_packets_proto = out.File
	file_api_proto_packets_proto_goTypes = nil
	file_api_proto_packets_proto_depIdxs = nil
}
