// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: character.sql

package db

import (
	"context"
	"database/sql"
)

const clearAuthToken = `-- name: ClearAuthToken :exec
UPDATE character
SET auth_token = NULL
WHERE id = $1
`

func (q *Queries) ClearAuthToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearAuthToken, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one
SELECT id, account_id, name, region, x, y, layer, heading, stamina, shp, hhp, deleted_at, online_time, auth_token, created_at
FROM character
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCharacter(ctx context.Context, id int64) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Region,
		&i.X,
		&i.Y,
		&i.Layer,
		&i.Heading,
		&i.Stamina,
		&i.Shp,
		&i.Hhp,
		&i.DeletedAt,
		&i.OnlineTime,
		&i.AuthToken,
		&i.CreatedAt,
	)
	return i, err
}

const getCharacterByToken = `-- name: GetCharacterByToken :one
SELECT id, account_id, name, region, x, y, layer, heading, stamina, shp, hhp, deleted_at, online_time, auth_token, created_at
from character
where auth_token = $1
`

func (q *Queries) GetCharacterByToken(ctx context.Context, authToken sql.NullString) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacterByToken, authToken)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Region,
		&i.X,
		&i.Y,
		&i.Layer,
		&i.Heading,
		&i.Stamina,
		&i.Shp,
		&i.Hhp,
		&i.DeletedAt,
		&i.OnlineTime,
		&i.AuthToken,
		&i.CreatedAt,
	)
	return i, err
}

const getCharactersByAccountID = `-- name: GetCharactersByAccountID :many
SELECT id, account_id, name, region, x, y, layer, heading, stamina, shp, hhp, deleted_at, online_time, auth_token, created_at
FROM character
WHERE account_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCharactersByAccountID(ctx context.Context, accountID int64) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, getCharactersByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.Region,
			&i.X,
			&i.Y,
			&i.Layer,
			&i.Heading,
			&i.Stamina,
			&i.Shp,
			&i.Hhp,
			&i.DeletedAt,
			&i.OnlineTime,
			&i.AuthToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
