// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: global_var.sql

package db

import (
	"context"
	"database/sql"
)

const getGlobalVar = `-- name: GetGlobalVar :one
SELECT name, value_long, value_string
FROM global_var
WHERE name = $1
`

func (q *Queries) GetGlobalVar(ctx context.Context, name string) (GlobalVar, error) {
	row := q.db.QueryRowContext(ctx, getGlobalVar, name)
	var i GlobalVar
	err := row.Scan(&i.Name, &i.ValueLong, &i.ValueString)
	return i, err
}

const upsertGlobalVarLong = `-- name: UpsertGlobalVarLong :exec
INSERT INTO global_var (name, value_long)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET value_long = EXCLUDED.value_long
`

type UpsertGlobalVarLongParams struct {
	Name      string        `json:"name"`
	ValueLong sql.NullInt64 `json:"value_long"`
}

func (q *Queries) UpsertGlobalVarLong(ctx context.Context, arg UpsertGlobalVarLongParams) error {
	_, err := q.db.ExecContext(ctx, upsertGlobalVarLong, arg.Name, arg.ValueLong)
	return err
}
