// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"
)

const getInventoryByParentID = `-- name: GetInventoryByParentID :many
SELECT id, parent_id, item_type, slot_x, slot_y, item_quality, item_count, last_tick, data, deleted
FROM inventory
WHERE parent_id = $1
  AND deleted = false
`

func (q *Queries) GetInventoryByParentID(ctx context.Context, parentID int64) ([]Inventory, error) {
	rows, err := q.db.QueryContext(ctx, getInventoryByParentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.ItemType,
			&i.SlotX,
			&i.SlotY,
			&i.ItemQuality,
			&i.ItemCount,
			&i.LastTick,
			&i.Data,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT id, parent_id, item_type, slot_x, slot_y, item_quality, item_count, last_tick, data, deleted
FROM inventory
WHERE id = $1
  AND deleted = false
`

func (q *Queries) GetInventoryItem(ctx context.Context, id int64) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventoryItem, id)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ItemType,
		&i.SlotX,
		&i.SlotY,
		&i.ItemQuality,
		&i.ItemCount,
		&i.LastTick,
		&i.Data,
		&i.Deleted,
	)
	return i, err
}
