// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID           int64          `json:"id"`
	Login        string         `json:"login"`
	Password     string         `json:"password"`
	Email        sql.NullString `json:"email"`
	LastLoggedAt sql.NullTime   `json:"last_logged_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Character struct {
	ID         int64          `json:"id"`
	AccountID  int64          `json:"account_id"`
	Name       string         `json:"name"`
	Region     int32          `json:"region"`
	X          int32          `json:"x"`
	Y          int32          `json:"y"`
	Layer      int32          `json:"layer"`
	Heading    int16          `json:"heading"`
	Stamina    int32          `json:"stamina"`
	Shp        int32          `json:"shp"`
	Hhp        int32          `json:"hhp"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	OnlineTime int64          `json:"online_time"`
	AuthToken  sql.NullString `json:"auth_token"`
	CreatedAt  time.Time      `json:"created_at"`
}

type Chat struct {
	Channel   int16     `json:"channel"`
	SenderID  int64     `json:"sender_id"`
	Region    int32     `json:"region"`
	X         int32     `json:"x"`
	Y         int32     `json:"y"`
	Layer     int32     `json:"layer"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"created_at"`
}

type Chunk struct {
	Region   int32  `json:"region"`
	X        int32  `json:"x"`
	Y        int32  `json:"y"`
	Layer    int32  `json:"layer"`
	LastTick int64  `json:"last_tick"`
	Data     []byte `json:"data"`
}

type GlobalVar struct {
	Name        string         `json:"name"`
	ValueLong   sql.NullInt64  `json:"value_long"`
	ValueString sql.NullString `json:"value_string"`
}

type Inventory struct {
	ID          int64          `json:"id"`
	ParentID    int64          `json:"parent_id"`
	ItemType    int32          `json:"item_type"`
	SlotX       int32          `json:"slot_x"`
	SlotY       int32          `json:"slot_y"`
	ItemQuality int16          `json:"item_quality"`
	ItemCount   int32          `json:"item_count"`
	LastTick    int64          `json:"last_tick"`
	Data        sql.NullString `json:"data"`
	Deleted     bool           `json:"deleted"`
}

type Object struct {
	ID         int64          `json:"id"`
	Region     int32          `json:"region"`
	X          int32          `json:"x"`
	Y          int32          `json:"y"`
	Layer      int32          `json:"layer"`
	Heading    int16          `json:"heading"`
	GridX      int32          `json:"grid_x"`
	GridY      int32          `json:"grid_y"`
	Type       int32          `json:"type"`
	Quality    int16          `json:"quality"`
	Hp         int32          `json:"hp"`
	CreateTick int64          `json:"create_tick"`
	LastTick   int64          `json:"last_tick"`
	Data       sql.NullString `json:"data"`
}

type Skill struct {
	ID          int64         `json:"id"`
	CharacterID sql.NullInt64 `json:"character_id"`
	SkillID     int32         `json:"skill_id"`
	Level       int32         `json:"level"`
}
